---
title: "VolcanicEruptionsAnalysis"
author: "Melanie Dube"
format: html
editor: visual
execute: 
  keep-md: true
---



# Volcanic Eruptions Analysis

## Abstract

This notebook examines data from a number of volcanic eruptions over the course of 2,500 years. There are a number of questions which can be generated from this data, including which volcano has the most eruptions, what region of the world has the most active volcanoes, what was the longest confirmed eruption, etc..

## Introduction

There are 5,589 total volcanoes which were have been added to this data set thus far. The observed volcanoes are located across the world, spanning all seven continents. There are a variety of classifications which volcanoes can fall into, including active, dormant, and extinct. The exploratory function for this set allows access to many different categories of data. The name and identification numbers (including eruption number and volcano number) for each volcano are listed, as well as eruption category. Additional data about the start and end dates of each eruption, and physical location of the volcano are also tracked in the data table.

## Reading the Data into Notebook

Always begin a new set of r with the library(tidyverse) code, as well and the data packages, which are pasted below.

Begin each new session by running the tidyverse and the package of interest.


::: {.cell}

```{.r .cell-code}
library(tidyverse)
```

::: {.cell-output .cell-output-stderr}
```
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.0 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
```
:::

```{.r .cell-code}
#install.packages("skimr")
library(skimr)

volcano <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
```

::: {.cell-output .cell-output-stderr}
```
Rows: 958 Columns: 26
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (18): volcano_name, primary_volcano_type, last_eruption_year, country, r...
dbl  (8): volcano_number, latitude, longitude, elevation, population_within_...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```
:::

```{.r .cell-code}
eruptions <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
```

::: {.cell-output .cell-output-stderr}
```
Rows: 11178 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): volcano_name, eruption_category, area_of_activity, evidence_method...
dbl (11): volcano_number, eruption_number, vei, start_year, start_month, sta...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```
:::

```{.r .cell-code}
events <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')
```

::: {.cell-output .cell-output-stderr}
```
Rows: 41322 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): volcano_name, event_type, event_remarks
dbl (7): volcano_number, eruption_number, eruption_start_year, event_number,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```
:::

```{.r .cell-code}
tree_rings <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/tree_rings.csv')
```

::: {.cell-output .cell-output-stderr}
```
Rows: 2252 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): year, n_tree, europe_temp_index

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```
:::

```{.r .cell-code}
sulfur <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')
```

::: {.cell-output .cell-output-stderr}
```
Rows: 2252 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (3): year, neem, wdc

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```
:::
:::

::: {.cell}

```{.r .cell-code}
#install.packages("tidymodels")
library(tidymodels)
```

::: {.cell-output .cell-output-stderr}
```
── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──
```
:::

::: {.cell-output .cell-output-stderr}
```
✔ broom        1.0.2     ✔ rsample      1.1.1
✔ dials        1.1.0     ✔ tune         1.0.1
✔ infer        1.0.4     ✔ workflows    1.1.2
✔ modeldata    1.1.0     ✔ workflowsets 1.0.0
✔ parsnip      1.0.3     ✔ yardstick    1.1.0
✔ recipes      1.0.4     
```
:::

::: {.cell-output .cell-output-stderr}
```
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Search for functions across packages at https://www.tidymodels.org/find/
```
:::

```{.r .cell-code}
my_data_splits <- initial_split(eruptions, prop = 0.5)

exploratory_data <- training(my_data_splits)
test_data <- testing(my_data_splits)
```
:::


We have specified eruptions (in the initial_split function), so that is the data which will be available. By changing this to one of the other five available data sets in the initial load, we can view different data.

By running exploratory_data, the table below is generated.


::: {.cell}

```{.r .cell-code}
exploratory_data
```

::: {.cell-output .cell-output-stdout}
```
# A tibble: 5,589 × 15
   volca…¹ volca…² erupt…³ erupt…⁴ area_…⁵   vei start…⁶ start…⁷ start…⁸ evide…⁹
     <dbl> <chr>     <dbl> <chr>   <chr>   <dbl>   <dbl>   <dbl>   <dbl> <chr>  
 1  344020 San Cr…   10882 Confir… <NA>        1    1976       8      29 Histor…
 2  241100 Ruapehu   14646 Confir… <NA>        1    1979       6      30 Histor…
 3  390030 Decept…   13182 Confir… N side…    NA    1800       0       0 Histor…
 4  211060 Etna      13732 Confir… East (…     2    1811      10      27 Histor…
 5  345040 Poas      11155 Confir… <NA>        1    1910       9      12 Histor…
 6  354030 Huayna…   11794 Confir… <NA>       NA   -7750       0       0 Radioc…
 7  357120 Villar…   21026 Confir… <NA>        2    1632      NA      NA Varve …
 8  283180 Azumay…   17929 Confir… Issaik…     1    1893      11       9 Histor…
 9  352040 Sumaco    11507 Uncert… <NA>        3    1650       0       0 <NA>   
10  373010 Grimsv…   12789 Confir… <NA>        3    1598      11       7 Histor…
# … with 5,579 more rows, 5 more variables: end_year <dbl>, end_month <dbl>,
#   end_day <dbl>, latitude <dbl>, longitude <dbl>, and abbreviated variable
#   names ¹​volcano_number, ²​volcano_name, ³​eruption_number, ⁴​eruption_category,
#   ⁵​area_of_activity, ⁶​start_year, ⁷​start_month, ⁸​start_day,
#   ⁹​evidence_method_dating
```
:::
:::


## Interesting Questions to Ask

-   What is the name of the volcano with the largest number of eruptions?

-   What percent of the total eruptions were confirmed vs. unconfirmed?

-   What are all different evidence methods and how many times were each of them used?

-   Are volcanic eruptions more likely to happen in one area of the globe?

## Data Exploration


::: {.cell}

```{.r .cell-code}
exploratory_data %>%
  skim(evidence_method_dating, data_name = NULL)
```

::: {.cell-output-display}
Table: Data summary

|                         |           |
|:------------------------|:----------|
|Name                     |Piped data |
|Number of rows           |5589       |
|Number of columns        |15         |
|_______________________  |           |
|Column type frequency:   |           |
|character                |1          |
|________________________ |           |
|Group variables          |None       |


**Variable type: character**

|skim_variable          | n_missing| complete_rate| min| max| empty| n_unique| whitespace|
|:----------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|
|evidence_method_dating |       635|          0.89|   5|  25|     0|       19|          0|
:::
:::


This uses the skim function to summarize data, by skimming the "evidence_method_dating" column we can see that there are 5589 rows, which should correspond to 5589 individual tracked eruptions. There are 15 columns, which could correspond to 15 different methods of evidence dating. This function does not show each of the names of the data collection methods.


::: {.cell}

```{.r .cell-code}
exploratory_data %>%
  count(eruption_category)
```

::: {.cell-output .cell-output-stdout}
```
# A tibble: 3 × 2
  eruption_category        n
  <chr>                <int>
1 Confirmed Eruption    4951
2 Discredited Eruption    92
3 Uncertain Eruption     546
```
:::
:::


This function shows us how many of each eruption category are tracked in this data set. There appear to be 4,964 confirmed eruptions, 80 discredited eruptions, and 545 uncertain eruptions. This could be useful data because in determining answers to questions about actual eruptions, it may be necessary to only look at the 4,964 eruptions which were confirmed.


::: {.cell}

```{.r .cell-code}
exploratory_data %>%
  count(volcano_number)
```

::: {.cell-output .cell-output-stdout}
```
# A tibble: 768 × 2
   volcano_number     n
            <dbl> <int>
 1         210010     1
 2         210020     5
 3         211004     2
 4         211010    13
 5         211020    33
 6         211030     9
 7         211040     8
 8         211042     2
 9         211050    23
10         211060   136
# … with 758 more rows
```
:::

```{.r .cell-code}
exploratory_data %>%
  count(volcano_number) %>%
  arrange(-n)
```

::: {.cell-output .cell-output-stdout}
```
# A tibble: 768 × 2
   volcano_number     n
            <dbl> <int>
 1         211060   136
 2         233020   100
 3         283110    87
 4         357120    80
 5         282110    78
 6         372030    67
 7         332010    57
 8         300270    54
 9         263250    52
10         300260    52
# … with 758 more rows
```
:::
:::


This counts the eruptions per individual volcano. By using the arrange function, we are able to change the way that the data is presented and organize it in descending order, so that the volcano with the most eruptions is listed first. This shows us that volcano number 211060 has erupted the most times (124). Because this is so much more than any of the others, it can be considered an out liar and could be worth investigating more.


::: {.cell}

```{.r .cell-code}
exploratory_data %>%
  group_by(volcano_name) %>%
  count(eruption_category) %>%
  arrange(-n)
```

::: {.cell-output .cell-output-stdout}
```
# A tibble: 1,043 × 3
# Groups:   volcano_name [762]
   volcano_name           eruption_category      n
   <chr>                  <chr>              <int>
 1 Etna                   Confirmed Eruption   110
 2 Fournaise, Piton de la Confirmed Eruption    96
 3 Asamayama              Confirmed Eruption    77
 4 Asosan                 Confirmed Eruption    75
 5 Villarrica             Confirmed Eruption    72
 6 Katla                  Confirmed Eruption    66
 7 Kilauea                Confirmed Eruption    57
 8 Klyuchevskoy           Confirmed Eruption    51
 9 Merapi                 Confirmed Eruption    51
10 Sheveluch              Confirmed Eruption    51
# … with 1,033 more rows
```
:::
:::


By running the code above we are able to see which volcanoes have the highest number of confirmed eruptions. It is evident that Etna has 100 confirmed eruptions, but there are at least 10 other volcanoes which have more than 50 confirmed eruptions.


::: {.cell}

```{.r .cell-code}
#install.packages("leaflet")
#install.packages("ggmap")

library(leaflet)
confirmed <- exploratory_data %>%
  filter(eruption_category == "Confirmed Eruption")
leaflet() %>%
  addProviderTiles(providers$OpenTopoMap) %>%
  addCircleMarkers(lng = confirmed$longitude, lat = confirmed$latitude, radius = 0.5)
```

::: {.cell-output-display}

```{=html}
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-6f06a9413e4b57370726" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-6f06a9413e4b57370726">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["OpenTopoMap",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircleMarkers","args":[[12.702,-39.28,-63.001,37.748,10.2,-16.608,-39.42,37.735,64.416,37.748,-39.3,-7.93,30.484,42.063,60.485,-1.52,63.633,54.756,12.423,52.315,42.688,19.514,46.2,1.358,-3.613,64.633,19.514,1.488,-0.38,10.2,-5.05,-6.62,36.406,51.79,-21.244,36.155,52.825,36.406,58.18,40.659,-2.005,64.05,-15.6,-21.888,14.473,-7.2,38.404,43.418,-15.6,14.473,-41.105,-9.62,9.979,20.708,37.748,53.256,24.285,38.404,37.748,-39.42,-7.93,9.979,52.825,34.724,-8.058,54.489,18.57,63.983,36.77,-2.764,14.809,58.336,-21.244,15.37,34.724,60.485,20.708,-7.54,-18.53,55.972,-21.244,-8.2,51.923,-4.08,-7.3,-0.38,58.236,56.653,54.489,13.434,37.804,-29.27,36.406,64.633,13.813,1.22,-16.294,51.923,14.95,-8.242,3.689,36.618,51.79,71.082,41.409,18.57,-7.2,64.416,63.892,3.138,34.724,12.278,36.618,54.32,-25.887,63.633,5.091,12.606,-25.887,63.416,-8.2,-8.108,-39.42,17.36,12.702,52.5,-37.52,63.633,32.884,64.633,-7.93,-39.28,10.83,55.832,35.361,-0.677,58.195,55.832,4.203,43.844,-50.964,-0.38,19.421,32.884,40.821,19.692,19.475,50.324,30.793,54.135,36.891,33.086,48.777,37.748,50.324,0.029,-37.856,1.112,-7.93,10.412,-5.05,-35.58,36.227,-16.507,-8.108,63.633,-33.425,39.853,15.63,30.793,-66.78,64.083,14.002,32.458,1.22,56.88,37.748,39.761,-7.2,64.267,38.144,-7.54,37.77,32.884,36.406,30.793,56.056,56.656,-57.8,19.692,-39.157,-19.75,37.748,39.853,43.384,51.873,64.05,-7.143,-38.379,-16.82,16.044,51.923,18.13,35.361,32.884,13.33,49.57,15.132,20.708,46.2,14.473,37.748,65.715,13.6,19.475,-39.42,28,0.8,40.51,34.724,-21.244,3.17,55.417,-16.82,-38.12,-0.979,52.381,-39.42,50.267,14.002,55.972,17.307,18.57,36.227,13.257,41.51,34.9,37.748,55.972,40.73,31.22,36.227,-21.244,52.559,15.13,-10.386,54.134,-10.386,-35.3,0.8,-8.108,32.884,56.056,0.8,40.821,-27.109,-2.005,28.271,15.255,19.475,-21.244,-38.82,-0.83,-1.464,-39.157,38.654,2.32,-39.157,38.654,-8.53,44.133,-7.54,-35.223,17.36,71.082,13.6,34.724,19.82,-16.355,-39.28,19.514,0.8,-0.38,64.633,19.514,11.985,-1.408,9.979,-16.82,17.36,-57.08,54.134,64.416,-39.42,64.633,31.934,-40.59,19.514,-8.058,32.884,10.2,32.884,-5.358,-1.408,27.247,44.076,-8.32,-0.904,36.406,-4.92,64.05,53.891,-2.764,34.094,-4.523,38.49,56.653,54.489,-6.77,10.025,-7.2,-1.697,-23.37,12.702,14.809,38.729,15.13,-0.83,56.17,-4.649,2.32,39.099,-35.223,54.049,-42.833,63.633,-8.108,37.748,-7.54,29.638,34.094,11.538,63.633,53.98,36.618,24.751,38.654,36.406,-16.355,1.352,11.538,10.83,35.233,33.086,-63.001,55.417,4.769,2.3,14.583,56.653,-11.75,43.572,55.972,14.95,1.112,12.606,36.586,54.134,31.593,33.282,51.577,12.3,34.094,10.412,-7.54,14.95,-1.408,-3.522,-13.8,-39.157,14.809,31.593,19.023,0.8,15.55,52.825,-3.522,19.85,-35.223,32.884,2.781,60.485,63.983,-21.244,-39.42,37.631,63.983,-49.019,64.633,-8.058,37.647,4.769,32.884,32.884,32.884,-38.692,0.8,-1.697,-8.108,50.686,58.236,19.514,-22.4,37.748,63.633,36.155,32.884,-7.942,45.95,-21.244,0.8,14.002,52.559,32.884,-39.28,63.633,1.358,19.475,47.35,31.888,46.2,0.029,50.686,-7.54,36.406,-38.12,60.485,-0.538,37.748,37.748,35.361,31.934,55.417,48.092,38.144,-7.54,-35.653,28.271,14.002,64.062,2.781,14.382,31.934,10.2,30.443,-0.077,42.544,38.654,14.473,31.593,12.769,43.418,-0.83,42.688,41.98,34.25,-8.991,36.586,-38.692,-6.77,-0.38,-0.83,-37.52,54.049,61.299,-6.976,37.748,28,42.688,-0.677,36.618,36.227,43.572,34.397,56.17,13.434,56.056,31.593,-1.697,43.722,38.729,13.434,10.83,-23.37,-18.166,-6.137,71.082,-39.42,13.257,56.056,-39.157,36.406,-39.3,40.821,-9.229,56.653,-7.942,-39.28,-1.506,13.434,0,11.985,13.257,34.094,13.33,-7.54,-1.467,-39.157,56.056,37.748,65.715,-13.612,14.583,-39.157,50.324,34.724,-11.75,55.417,36.618,-33.425,24.751,29.968,4.892,-7.2,-34.164,15.55,17.36,13.853,-7.93,34.724,63.416,34.25,-53.106,4.203,3.689,36.406,-21.244,48.292,37.748,-21.244,31.22,56.28,10.463,4.658,52.543,14.473,20.469,19.85,57.33,16.72,56.056,43.572,39.761,-77.53,-8.108,38.144,-37.856,19.421,-20.32,63.933,31.934,36.406,19.03,55.972,2.32,10.2,-4.92,17.36,-8.058,62.006,63.983,38.65,-7.54,36.406,14.382,-6.092,29.968,34.724,56.653,-37.856,-39.42,60.485,-7.3,16.044,37.125,36.406,-14.27,-15.787,-1.52,-21.244,28.797,10.83,-21.244,56.653,-3.613,19.421,36.406,19.023,56.653,30.443,-7.54,-0.38,33.137,15.13,14.809,-0.077,-6.137,54.756,34.724,-11.75,44.133,40.821,-0.83,42.688,64.416,19.85,-7.54,31.934,64.9,51.885,14.382,34.724,-5.576,55.832,63.883,-5.525,39.661,52.5,12.506,52.062,-63.001,55.972,-7.54,1.112,39.462,-6.137,1.358,-7.942,52.559,-11.75,14.242,17.05,14.809,-25.887,-21.244,6.37,-7.54,-8.365,1.358,56.056,56.88,10.2,64.633,0.02,-8.991,19.514,35.361,38.654,52.177,12.769,-38.692,56.88,-33.425,1.22,-35.745,1.08,1.5,63.883,46.206,51.452,13.257,50.324,52.559,19.421,1.08,-41.33,36.406,63.85,36.406,-21.244,13.33,1.38,37.77,-39.157,46.853,12.506,10.2,19.475,50.267,0,-0.677,49.57,-72.67,-7.54,10.463,-39.42,56.056,43.384,10.412,-0.171,37.601,-63.001,19.475,56.653,-0.38,4.892,35.361,-56.3,56.056,-16.82,38.404,-21.244,44.133,3.689,-8.272,50.686,-23.37,41.409,56.17,-11.75,-0.37,-19.75,39.964,55.832,-16.507,-5.525,64.633,10.025,19.475,29.638,-8.542,19.475,39.742,31.22,63.633,-25.887,-5.05,14.002,60.485,-42.799,-0.077,55.678,41.805,-21.244,-36.868,-7.242,-4.08,19.85,-38.692,1.22,16.35,13.813,52.559,36.406,-16.355,-6.102,-37.406,-8.991,45.1,41.805,-4.649,14.473,14.809,53.83,63.633,19.03,53.905,18.92,-5.525,12.3,-8.42,-42.377,-21.244,56.653,13.813,59.363,36.406,-8.817,40.492,-0.92,12.423,19.03,12.702,55.832,20.708,35.361,-38.692,43.979,63.633,55.832,-7.54,-37.52,9.979,-39.28,48.092,19.03,52.559,0,0.8,0.258,42.063,-6.895,64.416,12.606,-38.12,-25.887,13.434,-0.162,46.206,-38.82,37.735,1.518,63.633,56.653,-21.244,-42.799,59.363,-7.242,38.144,-37.52,-21.244,32.884,32.884,1.358,6.113,-8.108,58.236,32.884,-0.677,-8.108,-0.38,52.825,38.144,-5.525,53.256,4.769,37.748,1.112,36.799,0,52.643,11.985,37.6,-5.416,-7.32,64.633,-19.75,0,40.821,15.62,43.384,-7.942,31.934,-0.677,32.884,37.748,-7.242,-8.058,54.489,-21.244,63.983,-5.576,60.485,52.449,-7.981,-19.668,-39.42,36.406,4.903,-38.692,60.485,33.086,-5.05,36.406,56.653,55.832,2.781,1.112,52.559,14.473,41.611,-19.18,-0.171,7.691,29.638,-21.338,12.278,39.7,0,64.633,14.809,12.606,28,4.769,53.43,-39.157,-39.42,-7.942,57.05,-8.542,37.748,19.475,19.08,63.983,-0.171,33.137,56.056,46.853,-7.2,40.821,54.049,44.608,19.421,32.884,35.361,14.809,8.975,51.356,37.87,39.853,32.884,32.884,10.2,55.678,37.735,20.708,58.236,37.748,54.756,33.361,64.416,55.972,28.271,-20.536,-36.868,33.086,64.653,13.579,63.633,40.821,1.38,53.256,-4.523,-8.119,56.17,-9.13,37.748,54.134,-8.2,36.921,-6.77,14.002,35.361,55.55,-7.981,-4.523,54.756,35.361,42.688,52.825,-41.33,-1.697,17.37,52.825,34.219,55.832,-39.28,0,-16.294,37.748,54.516,56.653,32.458,19.023,19.514,-8.108,34.724,39.853,14.809,36.891,32.884,-10.386,38.73,60.485,34.724,-16.25,17.36,53.256,-7.3,0.8,0,33.197,56.056,55.972,63.633,32.884,-0.677,-7.942,37.748,-16.25,57.832,37.77,-7.942,-4.016,63.633,-8.108,-8.108,-39.42,-5.525,13.813,2.32,14.809,43.572,-8.342,-13.612,31.934,-40.35,56.056,30.443,37.804,50.324,-39.42,38.531,19.475,46.2,37.748,-1.408,37.78,10.463,40.821,-4.08,37.748,-1.458,40.821,-8.42,-77.53,60.485,40.827,19.03,19.421,-8.292,54.134,42.688,32.884,48.092,63.633,37.748,37.748,-16.25,-16.82,63.983,43.418,-8.242,-16.25,65.033,-11.75,-38.692,15.32,-8.42,-7.242,-0.38,-36.868,53.83,60.485,53.589,36.618,-16.25,-10.386,54.135,-39.3,64.9,28.271,-4.649,-23.37,-41.105,40.659,38.654,2.3,-39.42,-39.157,20.546,38.789,-2.764,54.753,-7.942,-8.108,43.722,24.751,9.979,51.885,54.974,40.51,44.133,56.056,63.892,19.475,63.883,-41.105,30.793,34.724,36.227,-7.942,-37.52,35.893,-0.677,-18.175,13.813,16.044,-39.157,19.08,19.023,62.006,39.099,-21.244,40.821,-6.137,13.257,14.382,48.777,50.267,64.583,-38.12,14.809,41.409,34.724,54.489,1.358,64.416,-38.379,54.134,-43.189,-28.98,-4.649,-16.82,14.95,38.404,-8.108,34.094,8.975,-4.523,-38.12,31.593,19.231,-39.157,37.647,36.406,-21.244,14.382,2.781,-5.525,12.606,-2.38,11.985,-15.787,10.463,-7.3,10.463,55.417,-21.244,31.22,37.77,0,16.72,37.02,-5.05,37.647,61.38,-8.108,36.618,12.423,-35.223,42.688,40.51,12.423,64.85,18.33,-42.799,-38.692,63.633,-5.525,-39.157,39.853,50.324,54.049,56.88,38.404,56.653,53.891,-16.25,55.417,-7.3,20.13,40.821,-39.28,14.473,-0.677,30.443,37.748,45.95,1.22,-1.697,38.961,-7.942,37.804,-0.37,54.134,36.155,14.473,-11.75,38.73,13.257,-38.82,14.473,63.633,65.583,-39.157,-1.467,-16.25,13.257,49.57,3.689,-20.73,-77.53,56.056,-18.175,-5.05,-39.42,19.421,-1.697,-8.2,-0.077,-26.789,56.056,12.606,-21.244,40.821,56.056,38.654,39.099,-25.887,31.934,39.853,32.458,-21.244,-25.887,0.029,-1.467,45.95,28.271,-0.38,10.748,63.983,-7.54,12.606,55.972,2.781,-39.28,43.418,-7.981,-39.28,37.804,33.137,64.083,-0.92,-11.75,37.87,-20.536,11.985,-7.242,31.934,-21.244,41.611,55.417,12.12,-39.927,36.404,36.699,19.514,-39.3,12.702,52.543,-7.54,37.87,51.93,-39.42,-6.102,46.853,-45.9,36.406,42.688,13.257,14.583,28.271,52.449,-39.157,10.412,-9.2,53.256,9.83,32.884,54.134,38.789,54.049,60.485,36.406,54.049,-7.981,56.17,1.488,39.761,59.363,36.227,-7.3,56.056,-20.98,-16.507,-0.677,17.6,-7.2,55.972,-16.25,38.404,42.93,4.658,28.57,37.748,37.735,57.33,-5.05,-21.244,56.58,32.884,-38.692,31.888,19.421,52.559,40.821,-39.28,55.417,-4.649,19.421,37.444,56.653,44.808,13.813,45.775,36.406,19.023,34.724,-8.991,60.485,34.724,53.256,63.633,31.593,-7.3,36.406,54.134,-0.677,-37.52,-39.157,37.748,40.821,45.775,-63.001,-7.54,24.751,-59.017,-0.677,32.884,-8.108,13.434,14.809,-13.612,-37.52,32.884,54.049,11.538,19.08,-7.454,58.28,-19.033,-0.979,58.172,43.384,60.485,24.751,2.32,-0.171,18.57,19.231,55.972,-38.12,62.006,-25.887,32.884,-22.33,-33.425,19.692,15.83,53.256,55.972,30.793,-7.93,-19.75,-7.32,52.713,50.686,12.506,52.449,-38.692,32.884,37.748,0.02,19.08,31.22,56.653,35.361,-21.244,-2.764,13.813,-7.54,-15.1,19.421,52.825,38.73,36.106,56.056,-49.019,-36.868,2.3,-21.244,-5.525,-25.887,19.82,42.063,-40.59,19.514,20.546,-42.377,31.888,36.406,13.257,-7.93,-21.244,-21.244,14.242,46.206,-18.1,-4.016,-0.37,10.412,63.633,-18.325,-76.05,-7.54,-45.9,50.324,64.416,-0.077,-8.676,-4.016,42.688,1.22,43.418,-16.68,-38.692,2.781,21.93,64.416,33.361,66.309,4.818,39.964,63.733,12.506,19.475,37.748,-39.42,51.45,2.93,-7.54,-0.92,36.406,32.884,34.724,-0.171,55.972,0.029,6.37,4.203,37.748,56.056,31.934,32.884,-0.677,0.8,12.606,37.748,20.708,37.748,1.22,-18.42,32.884,-19.75,31.934,31.934,36.406,-16.355,-15.6,51.79,42.827,-0.38,-7.3,64.633,-35.223,-29.27,11.985,44.353,29.638,16.72,63.633,14.809,-21.244,24.285,11.985,56.653,12.423,14.583,-63.001,-17.026,56.17,0.029,9.83,33.874,55.832,63.983,40.73,-39.42,2.32,30.793,-38.379,56.056,34.094,-6.77,-33.425,32.884,52.449,52.177,13.434,-0.979,37.748,4.892,56.056,-0.38,44.133,10.2,37.87,1.112,-25.37,0.32,40.73,31.593,32.884,-1.697,-7.2,64.416,37.804,37.748,60.485,54.134,19.023,31.934,60.032,37.748,36.406,40.827,65.416,27.247,-38.42,54.756,36.406,-7.54,-39.42,-7.54,34.094,-0.677,-18.42,-6.77,38.73,-2.414,-8.542,9.83,13.813,14.473,34.724,15.307,36.406,-39.42,63.983,37.748,0,-8.32,0.792,31.22,-38.12,34.724,2.781,51.306,35.361,24.751,-1.467,-8.108,19.475,43.722,20.469,54.134,-8.2,-18.023,13.813,54.135,53.256,-6.102,2.781,50.267,28.271,-39.157,-39.28,47.95,14.473,-21.244,56.056,31.934,-18.754,-16.82,55.417,-6.52,-7.942,2.32,54.134,41.805,-0.677,-39.28,-39.42,63.983,-7.981,40.827,54.65,33.137,63.983,36.406,53.891,37.77,39.853,20.546,52.449,54.135,-8.32,-39.42,-16.829,56.88,64.8,-37.52,36.404,45.93,49.57,-8.108,14.473,-41.105,-7.981,-8.242,-7.95,-0.677,52.449,56.653,27.881,-0.38,2.32,24.751,-6.77,56.653,-7.942,45.374,53.905,64.416,55.972,-39.42,-8.342,-4.523,52.559,13.813,54.049,13.6,37.748,12.702,-14.27,-33.789,13.579,54.049,-20.32,15.132,36.406,15.37,40.827,13.33,36.921,-36.868,-15.6,-0.677,60.485,37.748,31.22,36.406,50.324,-52.33,-0.979,39.964,19.475,9.979,1.112,-6.77,-8.2,32.884,36.618,-37.52,-14.215,37.804,44.43,-1.408,37.748,19.421,60.485,19.514,54.596,-11.75,-41.33,36.406,29.03,-20.852,30.443,12.769,-1.467,-19.15,-38.379,14.002,65.033,34.094,40.821,19.08,38.144,19.514,-10.386,9.979,-7.54,46.532,-7.942,-7.54,19.023,13.257,52.559,54.756,47.77,-38.692,14.809,14.382,43.42,37.748,-0.92,52.825,55.832,31.934,56.653,-0.39,-21.244,-8.817,55.417,39.964,-8.2,-39.3,4.903,-23.37,38.144,1.358,54.134,55.832,-8.891,40.827,19.023,56.056,-0.677,51.844,-33.425,-5.358,4.892,4.892,34.724,64.8,49.57,45.012,37.748,-38.692,57.05,40.656,42.544,12.606,52.315,-21.244,2.3,14.757,38,64.416,43.418,-4.08,55.972,54.049,63.633,55.417,-2.764,-39.28,1.352,43.42,-35.223,61.64,63.633,12.606,-21.244,0.686,-0.171,19.421,-37.52,31.22,-39.42,31.934,-5.094,31.934,36.618,37.748,-50.33,71.082,39.356,52.449,-1.408,-7.54,31.934,21.93,14.473,10.412,36.618,65.715,-4.016,-2.764,-7.981,51.79,-16.25,56.056,12.606,-8.272,37.748,-5.576,20.708,-5.576,-8.542,46.52,49.12,58.195,13.257,3.588,-8.32,-0.83,60.485,12.506,64.85,-21.244,-8.891,31.593,33.086,46.2,-39.25,-63.001,14.809,19.67,19.108,-38.97,-39.42,-8.991,18.13,56.056,-4.08,37.748,-5.05,37.748,19.421,15.32,12.702,27.247,19.692,38.404,32.657,46.532,43.664,13.33,-8.108,-8.242,-4.016,60.485,-39.157,52.559,19.475,-0.37,34.724,10.412,-39.28,-18.1,64.633,40.821,54.134,1.5,-10.386,38.961,59.363,28.271,0.8,-21.244,63.633,60.485,-40.59,14.382,31.934,43.722,-39.887,10.463,-0.677,3.689,46.815,55.417,-1.697,12.769,-21.244,-5.05,0.8,-0.979,2.32,55.678,20.708,31.934,19.475,34.724,38.404,-43.497,2.781,3.17,39.761,37.748,-4.523,-7.942,19.475,-8.2,13.257,-6.77,40.827,-7.242,-39.28,-0.914,28.271,-7.942,-17.436,56.653,-1.697,37.748,-1.697,-42.833,-3.522,-0.37,33.137,63.983,53.13,-0.38,10.412,-1.467,54.049,-4.08,10.2,-8.32,42.491,-5.519,0.8,20.708,32.761,12.506,56.653,48.873,-16.82,19.475,-1.464,52.381,-6.77,-15.6,-39.157,-39.42,-0.171,-0.83,36.406,36.227,12.495,29.968,58.195,0.308,-33.789,-38.42,24.751,-7.54,14.809,55.972,36.921,54.134,-20.536,64.416,56.17,-8.42,-16.25,-1.467,-7.143,-24.72,20.708,56.056,29.638,-21.244,-25.887,32.761,64.633,3.138,12.506,-8.108,-16.82,0,-8.991,41.51,11.985,-0.22,20.13,36.618,-35.223,-38.692,12.702,19.421,12.506,-21.244,-19.15,-8.108,-0.38,11.985,19.421,52.559,-0.38,32.884,63.633,-0.43,32.884,-29.27,-0.979,12.506,57.135,40.73,0,16.044,13.813,-39.42,-4.016,-0.38,53.905,34.724,14.002,-4.016,39.099,64.9,-13.612,32.884,-21.244,64.267,53.256,12.769,-16.25,41.98,-1.408,42.688,11.538,34.094,19.514,-1.464,-29.27,28.271,46.2,42.688,-39.42,36.77,-7.981,63.633,47.02,-29.27,44.38,-21.244,-16.355,-7.981,52.559,43.615,38.404,19.514,0,-6.77,43.418,48.092,-52.33,-21.244,18.57,37.748,0.8,34.094,34.724,12.769,13.257,19.692,65.416,11.538,19.421,19.03,57.72,64.083,37.748,-16.25,55.832,31.22,53.93,65.033,55.417,10.463,53.93,-7.54,51.356,-7.625,12.606,-16.355,-39.3,36.618,43.979,36.406,-21.244,-8.108,19.692,28.271,-8.25,42.688,-15.389,-21.244,40.821,52.559,-0.171,-18.325,54.134,-53.106,40.827,-4.016,60.485,-8.108,36.404,-21.244,14.002,19.023,54.049,-6.137,13.434,14.501,19.475,45.775,37.748,37.647,-8.108,36.227,48.112,18.13,4.892,14.382,1.693,32.884,53.83,63.983,34.724,-6.137,47.02,-6.77,37.804,13.434,64.633,-7.242,-2.005,0.02,56.653,63.733,37.748,0.8,53.256,30.443,34.9,9.83,54.761,63.892,-38.692,33.137,63.633,39.853,19.514,60.485,19.514,55.417,19.514,36.586,0.029,52.449,37.78,63.983,-6.102,-35.223,-1.697,50.686,-15.787,-28.98,55.972,32.884,0.8,-21.244,58.354,-21.244,-18.023,56.17,-41.105,31.934,-6.312,2.32,63.633,3.689,56.653,10.2,-21.244,-39.3,-38.97,-1.458,9.83,13.813,-38.692,14.809,-77.53,37.748,-7.93,19.421,13.813,38.144,12.702,42.063,46.042,36.618,-1.697,-6.137,-8.242,-16.25,17.36,36.406,51.93,51.923,-4.649,-0.677,36.921,0.75,2.781,2.781,-39.42,-39.42,45.95,-6.102,-41.33,52.381,27.73,37.748,10.2,63.85,51.923,38.75,19.023,37.748,19.023,2.781,13.813,-36.868,11.985,-21.244,56.056,55.424,-17.662,36.406,52.315,19.514,-41.33,37.748,-39.157,12.702,34.094,14.473,54.049,56.056,26.127,2.781,31.934,53.256,36.406,1.22,-16.507,13.813,-1.697,-1.408,0.8,-16.82,-7.93,36.406,52.825,-0.22,37.78,60.485,-6.102,-39.637,38.144,0.029,-38.692,55.972,63.983,14.797,-77.53,30.793,51.923,-14.27,-7.242,-5.05,0,19.421,4.818,37.735,36.406,20.708,-7.942,41.409,53.891,-5.525,-4.016,28.57,63.983,55.832,-8.991,31.934,8.808,-38.82,19.514,63.883,48.777,19.475,-0.677,-8.342,-0.38,-16.25,0,13.434,-38.12,55.832,19.421,14.809,33.137,38.65,-39.42,37.78,-77.53,-40.783,13.813,39.761,-21.244,37.748,-39.3,-7.54,-1.408,-8.991,37.748,51.356,14.002,-11.75,-1.408,54.65,-38.31,63.633,40.73,10.83,10.83,20.708,37.87,42.688,19.421,63.633,53.256,-38.692,0.8,0.029,34.724,10.83,39.7,-17.662,-42.833,15.13,37.77,19.475,-5.05,63.633,36.921,-41.33,14.473,14.809,-29.27,51.844,42.67,64.416,37.748,52.449,28,39.099,37.77,43.42,19.023,-10.386,33.086,19.475,-4.08,37.5,55.131,14.809,12.506,2.781,-0.92,-16.82,55.832,-21.244,37.748,60.485,55.972,44.133,-39.28,-21.244,64.8,46.2,-16.755,37.748,57.832,-8.542,31.593,12.702,56.88,-7.981,64.416,54.134,-2.005,9.83,0.029,-39.3,7.77,-8.119,30.484,-39.157,63.983,30.484,37.748,39.797,0,13.853,11.985,56.653,36.406,-1.408,60.485,64.583,-41.874,19.023,34.724,10.412,-7.981,-39.3,14.809,-39.157,-21.888,37.87,-5.05,55.417,56.056,34.724,18.13,0.8,10.83,35.361,-33.789,19.421,63.633,1.5,36.227,10.2,36.406,0,64.633,56.653,-6.102,55.131,55.832,-7.2,35.361,-0.677,-6.102,-38.31,-57.08,14.797,37.748,44.83,36.155,-36.868,39.853,-2.764,-6.102,48.092,13.813,49.57,55.832,1.112,-4.08,-28.98,-8.32,38.537,-16.25,12.506,65.715,13.734,1.112,25.424,47.52,63.633,9.83,10.2,10.2,14.809,-29.27,50.686,63.633,-19.18,-4.08,44.076,-8.119,57.55,-19.18,-2.005,54.756,-39.42,-7.2,36.406,-0.481,-8.32,-7.54,56.653,39.761,-3.613,14.809,-8.119,51.533,-11.75,63.633,37.87,65.715,-6.102,32.884,-5.05,14.002,-8.119,53.256,48.777,-19.12,52.559,13.813,50.17,19.421,-38.12,12.423,31.593,-4.271,7.691,-5.416,0.8,-8.108,-39.496,5.091,19.023,-7.981,54.134,51.923,37.735,41.611,52.449,-0.677,-7.981,-7.942,1.358,54.596,12.242,38.789,-33.789,31.934,-8.272,-23.37,-8.119,63.983,12.606,-0.677,50.324,54.134,0.029,-0.38,0.8,-10.386,13.58,42.688,10.83,-8.108,28.57,-40.783,19.421,19.421,13.257,-21.244,-23.37,53.256,63.633,65.033,61.64,-16.507,55.678,-7.942,48.958,37.748,-1.408,-53.106,52.315,47.35,32.884,10.2,-8.991,10.2,49.57,54.596,50.861,-33.425,-1.52,28.271,-19.75,-38.692,15.32,-6.312,32.884,13.257,6.113,19.421,56.17,-5.05,-18.1,37.735,38.6,2.781,-1.697,56.653,45.775,13.434,-39.28,0,-0.38,54.596,52.381,56.056,36.406,-7.942,20.708,-39.42,13.33,3.689,-7.242,12.506,14.002,42.544,28.57,-4.649,36.406,55.972,54.134,33.086,4.892,37.748,13.257,2.781,-39.28,-39.42,-7.733,-6.102,-19.15,20.708,55.131,-8.42,-7.242,0,-25.37,60.032,-21.244,-40.59,37.748,10.83,-21.244,53.256,56.653,-0.677,36.406,12.606,13.257,63.633,-39.157,35.233,39.284,-0.171,54.135,19.421,-0.38,40.821,48.98,36.106,-21.244,-4.271,53.43,43.615,38.144,-39.42,58.172,32.884,12.3,52.643,61.299,54.049,19.421,-0.677,-6.102,1.358,48.112,-4.649,65.715,33.361,56.17,35.361,53.589,14.473,-7.143,60.032,-6.102,-45.9,63.933,56.653,-62.1,51.452,-7.54,56.653,54.756,-39.42,27.247,-39.157,63.983,35.233,-16.829,-1.52,-41.33,8.808,-8.542,-8.991,-38.692,12.606,44.133,46.2,-0.979,63.633,38.144,36.404,1.112,19.421,-25.887,38.654,2.3,-1.52,19.023,-39.28,13.813,13.257,56.78,14.002,36.618,19.514,53.256,54.761,60.485,54.049,42.688,34.397,-38.82,36.406,24.751,18.13,65.715,46.2,-4.271,-40.59,0,-2.764,14.473,10.73,10.025,-38.692,65.715,-7.93,-40.59,-39.157,32.884,55.417,43.57,33.137,37.748,53.43,39.761,24.751,31.44,-17.436,55.972,-0.914,-0.077,-7.942,-7.942,64.633,38.789,10.412,51.844,54.528,-39.28,-39.157,-8.2,63.883,37.748,63.633,63.633,-41.33,19.514,-6.77,63.633,31.934,21.125,44.353,-0.677,-5.358,-6.895,19.475,1.112,36.571,14.002,40.821,20.42,50.861,54.756,42.063,-8.119,37.735,-9.57,-10.386,54.756,-47.2,34.724,36.155,51.356,32.884,32.333,-0.171,-16.25,36.227,52.449,19.475,10.2,63.633,32.884,14.382,52.559,0.8,-21.244,46.2,37.748,52.825,-4.271,-53.03,49.12,-50.964,63.85,0,54.489,4.658,37.748,53.256,52.825,13.813,45.95,45.95,-8.108,30.443,37.748,33.874,-8.73,-0.677,64.083,14.002,0,46.2,35.361,5.448,-18.806,40.656,-1.467,-59.442,-20.536,34.724,12.278,17.36,40.73,64.05,19.421,48.873,-8.542,54.489,-39.42,13.33,55.832,60.485,37.748,-7.791,43.722,52.315,45.389,32.884,37.748,-0.077,37.6,29.638,63.983,-16.25,10.2,-7.54,-5.05,-7.2,-7.981,32.884,55.678,12.702,1.22,31.934,-39.3,-39.42,11.538,-7.942,46.2,-37.856,-0.38,54.049,-7.54,13.257,-8.242,19.421,36.406,-16.507,56.056,37.748,-66.78,-9.135,0.029,64.083,54.049,-6.102,12.606,-1.408,55.832,43.572,-5.519,40.656,32.884,-37.856,63.633,13.37,36.227,53.43,32.884,31.934,-24.72,19.08,0,55.417,19.514,-1.52,56.653,37.748,-8.25,42.688,63.85,-10.386,-39.42,19.023,-16.82,1.38,-21.244,34.724,29.638,51.577,18.92,64.633,64.05,-23.37,-2.764,-8.991,-38.692,19.514,10.83,-37.52,55.972,11.985,19.475,60.485,-6.77,64.416,60.485,1.358,52.449,-7.942,-6.77,19.023,56.653,-4.016,-16.82,31.934,30.443,-14.215,63.983,13.813,33.78,-21.244,55.832,-8.2,-1.52,37.748,-1.697,16.044,14.002,39.761,13.257,23.08,-16.355,19.692,13.734,-13.612,9.979,12.423,1.358,-40.59,34.094,36.618,0,36.921,39.761,14.809,56.653,51.844,36.571,-63.001,32.884,53.589,13.257,54.596,-7.54,0.8,31.593,53.891,-7.54,-7.93,19.73,-6.102,24.751,-17.564,52.315,-39.157,-41.33,64.8,37.58,1.112,16.044,-5.576,14.501,51.498,33.137,-13.8,54.516,13.434,34.724,19.514,-39.42,52.559,56.17,17.63,60.485,-7.981,37.87,54.756,-39.42,56.056,19.514,50.324,34.094,-52.33,64.8,14.473,63.633,-1.52,63.633,-2.764,31.22,12.606,40.827,0.029,0.8,36.618,-11.75,38.789,19.514,-39.28,31.934,-1.52,32.884,14.473,14.382,-11.75,-39.42,53.256,52.22,5.203,-0.677,37.748,55.417,-7.25,56.653,40.827,36.406,11.523,-35.653,26.127,40.659,52.559,28.271,54.596,44.285,-16.82,-7.93,42.688,-11.75,-21.244,40.821,-8.891,0.792,28.271,3.689,-28.98,-5.525,56.28,-8.62,35.361,1.112,19.475,55.972,57.97,43.418,14.382,-59.017,-8.95,55.832,0.32,14.809,-37.52,57.27,-8.53,29.638,52.449,44.353,53.98,19.03,4.818,-8.42,19.514,44.43,53.83,12.702,36.227,40.028,40.73,-42.799,59.363,-39.3,55.972,39.853,19.523,-0.677,63.983,0.8,34.724,-77.53,2.3,-7.54,39.761,36.618,56.056,2.781,-18.166,-38.12,27.881,53.93,31.593,14.382,64.8,16.35,13.257,-15.389,-39.157,19.421,31.934,55.832,-21.244,46.925,4.892,36.406,19.231,-11.75,40.821,-23.37,55.832,32.884,-8.62,43.418,64.05,-6.72,40.659,35.141,13.672,-4.016,-5.358,-39.42,4.903,-39.42,40.492,-5.358,1.358,-37.28,40.821,28.271,14.473,37.601,55.832,10.412,63.983,-8.108,16.72,-8.991,-6.312,38,63.983,65.583,56.653,38.404,19.475,43.418,-0.37,-16.25,54.596,52.315,11.985,55.131,13.813,52.559,55.12,0.8,-16.507,29.638,56.056,32.884,-0.677,11.538,14.002,54.596,40.821,-39.28,39.964,-0.37,14.95,-8.508,14.002,19.421,30.793,1.5,-8.242,10.2,-45.9,45.775,-7.143,56.056,34.094,-49.019,36.406,-16.82,19.692,-16.82,38.404,-6.72,34.724,32.761,1.358,52.449,64.083,43.384,-0.375,-3.522,-0.38,10.2,10.412,-0.83,-7.54,20.708,-21.244,12.278,37.748,4.658,-16.82,-8.119,42.544,44.133,18.13,1.358,48.092,-0.38,-38.692,54.134,32.761,54.049,48.777,18.13,10.025,24.751,32.884,64.85,37.1,20.708,46.52,24.751,-0.077,-7.242,-0.677,53.891,-39.42,-5.05,-15.6,-14.295,-8.108,-36.868,1.358,-29.27,14.583,-21.244,-6.102,31.934,19.475,-12.83,-39.42,-0.077,1.22,-19.532,42.688,36.406,13.434,-3.613,-7.942,63.633,2.781,37.601,63.633,-16.507,37.748,53.98,9.203,-39.28,54.049,50.324,36.406,-21.244,-5.05,36.227,-39.42,52.449,-45.9,44.076,35.361,-38.692,51.844,13.257,31.888,55.972,55.131,16.35,-6.976,-0.38,15.62,-15.389,40.656,46.2,7.691,56.056,-1.52,58.608,48.133,12.606,19.692,-6.77,-21.338,1.518,-4.08,36.406,12.606,52.543,-0.677,56.653,-39.42,12.3,3.689,-4.08,-21.244,-39.28,-16.507,56.056,40.827,11.985,65.715,64.083,-0.171,3.588,63.633,56.113,12.3,13.813,63.633,-6.77,31.593,40.73,-8.119,-21.244,-8.991,-0.171,60.485,-0.38,-0.37,36.406,19.475,53.905,40.821,-8.53,45.1,54.049,35.361,13.434,46.853,52.22,-21.244,-7.54,19.514,-6.137,38.144,54.516,19.08,-8.119,-11.75,63.983,19.514,64.416,17.36,-0.38,-21.244,63.633,36.77,38.144,-41.33,36.227,53.256,-16.507,11.538,41.805,49.57,65.583,13.434,-39.42,39.099,32.884,38.49,46.2,33.086,-38.82,49.12,-4.523,19.475,19.421,-39.496,13.853,19.514,1.358,63.633,31.934,-41.105,38.404,19.023,43.384,-38.692,-21.244,55.678,31.593,-7.942,-0.677,56.056,-7.143,36.477,4.903,59.363,63.983,-0.02,-2.38,63.633,55.832,45.012,-8.991,-5.05,-32.958,34.9,-41.33,-38.12,4.203,54.756,63.633,56.653,-39.3,15.05,63.633,-39.28,-16.25,64.653,-38.12,55.972,1.358,-7.54,54.135,20.708,-14.27,-74.33,0,2.63,28.57,-33.425,-7.143,37.5,10.2,-37.52,-15.389,-7.54,-0.38,18.13,-77.53,43.384,-6.77,0.02,-4.08,63.633,19.523,19.85,36.406,-16.355,10.2,-18.992,-2.68,55.972,52.559,-0.171,10.025,-8.343,54.135,-7.125,13.813,10.285,-39.42,4.658,65.833,-8.42,-18.53,-21.244,42.544,-37.092,38.789,52.449,53.93,45.95,12.606,39.356,52.559,-41.33,-39.42,43.615,-21.244,-0.077,-21.244,14.473,31.934,56.88,-8.272,55.832,55.972,56.056,36.77,36.406,56.653,37.748,-6.312,36.406,10.463,-37.406,10.2,35.361,54.756,-8.108,40.821,37.748,-4.523,51.844,-0.677,5.091,24.132,-3.25,43.418,19.421,-8.508,64.9,-7.25,64.633,-2.764,54.049,43.664,56.653,56.653,-15.787,-38.12,42.063,-8.108,55.678,55.832,-16.294,1.15,-8.53,-0.677,31.934,-39.42,52.449,38.144,9.83,14.473,14.473,35.361,12.3,13.83,-12.83,20.546,51.885,54.756,19.514,51.79,-0.171,19.514,55.972,20.708,32.884,19.514,-15.6,36.406,56.17,14.382,40.659,56.056,-8.119,35.361,2.93,-3.522,-8.53,39.853,64.653,53.256,12.606,-38.692,43.384,-16.355,37.748,38.729,38.144,-37.77,-35.223,30.443,-39.157,55.972,64.416,38.144,-4.523,-39.28,40.656,53.43,-6.102,19.421,-8.25,-40.59,19.023,45.012,-11.75,-39.157,12.12,19.514,-38.82,-7.242,-8.108,0.32,14.95,-16.82,-37.406,-8.991,10.2,29.638,51.885,20.708,-1.52,13.434,-13.612,13.257,35.233,-0.077,37.748,-16.294,52.5,-39.42,-0.914,35.361,54.5,31.22,34.724,12.12,10.2,-38.692,34.094,52.076,63.633,39.95,53.891,-38.692,-1.467,2.32,11.985,-39.42,56.056,36.406,31.593,-38.12,-38.12,0,1.518,36.921,-3.522,-11.75,2.781,19.475,-0.677,38.654,-6.102,4.203,38.404,-2.764,11.538,65.833,53.13,-37.856,-7.981,-23.37,19.023,0.029,39.462,0.8,28.271,-6.77,54.135,-41.33,55.417,13.257,13.33,50.686,-33.425,10.463,42.688,30.443,-8.119,19.85,48.98,-6.102,43.418,-4.08,-39.42,-2.764,37.748,52.5,-5.05,4.892,2.781,-38.12,4.203,10.83,43.42,19.023,65.033,13.813,19.475,63.983,52.076,21.93,13.813,11.985,-0.38,-0.38,16.044,54.134,-0.677,54.596,-0.677,64.416,13.434,9.83,19.692,32.761,0,35.233,-0.171,18.13,38.404,19.421,-13.612,-0.677,55.972,13.257,34.724,64.416,54.134,34.724,37.748,36.406,37.125,36.227,-35.223,14.002,19.421,46.2,34.724,-18.166,-19.532,36.406,-1.408,37.748,-0.83,-41.33,53.321,-24.396,30.793,32.884,56.056,36.404,37.748,0,19.421,13.672,-0.677,-7.981,63.983,63.983,52.449,10.412,63.633,13.813,37.748,-41.33,63.892,-5.576,55.417,-18.023,19.421,14.382,-18.166,48.092,-7.2,-39.28,13.813,51.923,4.203,63.933,-8.119,19.077,46.853,-8.242,-0.077,-0.38,36.765,43.384,-39.3,8.808,52.103,38.404,-8.108,2.32,-2.764,55.972,18.13,33.282,36.406,34.724,-6.77,-8.542,-39.157,56.653,59.363,19.523,37.77,54.761,32.884,10.158,39.964,-57.08,-7.981,-37.77,-8.365,63.983,-16.25,20.546,63.983,53.891,38.404,15.132,-7.942,-21.244,19.421,0.308,41.611,4.658,5.091,-8.108,-8.108,-39.28,36.155,63.883,-7.54,55.678,-8.77,40.827,36.406,11.538,37.87,64.416,-38.12,63.85,59.363,-7.93,-22.33,31.593,-5.05,-41.33,-20.32,28.57,-8.542,-0.677,56.653,42.67,19.421,-33.425,9.979,56.056,40.656,-8.53,19.475,64.416,19.475,57.72,-40.59,32.884,19.475,11.985,-36.422,-6.137,31.934,32.884,13.434,13.257,-1.52,39.958,36.618,1.352,63.633,38.144,38.6,-11.75,53.891,55.417,-0.077,-0.37,19.421,14.382,-5.576,-4.016,-8.119,-4.271,31.934,45.389,19.023,14.473,-37.52,44.133,48.112,-8.119,19.514,-16.294,53.256,-16.82,63.85,-6.72,24.751,19.421,-4.016,54.756,37.748,38.144,52.559,14.473,65.416,30.793,-7.242,-39.42,46.532,-39.42,41.409,13.257,56.653,32.884,41.409,-16.355,54.596,42.688,-6.976,-21.244,-39.3,48.292,64.8,0,54.756,43.147,-53.106,36.155,55.417,63.633,38.144,-16.355,48.092,20.546,-8.991,15.55,34.724,46.2,1.112,-53.106,-21.244,-7.2,-21.244,10.463,56.653,0.02,-2.764,64.416,10.463,-0.171,37.748,-36.058,43.351,40.821,48.092,46.206,-4.523,1.352,-6.102,-8.42,0.8,-1.697,36.087,-4.08,4.892,37.748,-7.242,45.88,-39.42,40.98,-2.005,4.487,32.884,55.832,17.478,64.8,11.538,-36.193,37.748,19.475,17.36,9.979,11.985,-23.37,-39.42,54.756,-0.37,63.633,4.487,15.13,28.271,19.03,-8.108,-18.1,19.514,64.083,-0.375,-54.97,28.57,4.487,34.397,40.827,-15.83,-7.54,31.593,0.32,12.506,20.33,18.77,-4.12,63.733,57.135,-38.692,10.83,-33.425,-0.83,54.596,42.93,-16.25,-7.93,55.417,-5.525,54.489,28.271,-0.677,-8.119,12.3,60.485,-8.242,42.063,11.538,52.559,49.12,37.748,0,9.979,32.884,53.256,40.821,16.72,-25.887,-0.077,-28.98,31.934,13.853,54.65,54.761,-37.856,2.781,-8.119,36.618,31.888,-33.425,-5.05,14.809,35.361,19.514,60.485,56.88,-6.77,19.514,-8.119,14.002,37.748,12.606,-36.9,43.42,-16.25,9.83,-7.93,56.653,-36.868,19.421,-0.677,-50.33,-0.38,55.972,0.32,-1.467,25.178,-7.942,32.884,39.099,65.416,63.85,-6.102,46.853,-8.119,46.532,-8.343,19.421,53.256,-7.981,58.27,31.593,42.875,0.32,23.5,34.724,63.883,55.832,-21.244,-16.82,36.891,65.583,46.853,53.93,42.688,-2.005,12.702,9.203,37.735,-21.244,1.22,-3.613,-21.244,-10.386,-8.891,-8.108,-23.37,-21.244,-5.094,54.049,40.73,63.633,38.654,37.748,14.809,53.589,55.972,52.449,64.653,-21.244,16.044,-39.42,-0.677,-16.355,13.434,43.384,19.421,36.618,-42.377,34.724,19.421,52.825,54.756,19.421,36.618,31.934,50.861,-2.005,71.082,13.813,19.077,-36.058,9.83,12.702,36.406,0.32,65.715,-0.677,36.404,37.748,-35.745,56.056,-7.242,40.492,-4.08,-6.137,55.972,38.144,-8.108,-8.542,-6.77,53.321,-4.523,-16.294,-37.856,61.299,56.011,36.227,0.02,-1.467,12.38,10.412,36.406,-39.3,20.708,19.421,-23.37,-6.77,40.656,60.485,-6.102,-39.42,-39.637,54.756,-36.868,18.13,-38.72,63.983,19.421,37.804,14.473,-35.223,37.748,34.724,37.748,-8.817,-38.692,64.653,41.98,-1.408,20.546,54.756,10.463,36.406,-11.75,38.404,37.748,19.03,42.7,-6.895,54.049,19.514,-8.119,47.45,2.781,63.633,52.33,-6.77,29.638,60.032,27.881,19.421,53.589,56.653,56.056,41.611,60.485,19.421,34.724,19.421,63.883,-21.244,55.832,-38.12,1.22,63.85,50.63,35.361,65.033,56.653,31.593,-10.386,11.538,-21.244,46.853,-16.25,-38.692,40.827,19.03,-45.9,4.487,63.883,-21.244,40.821,32.458,56.056,63.733,55.832,38.654,-37.406,54.761,63.85,63.983,14.473,-0.53,30.793,-8.108,-28.98,-38.82,57.72,24.57,19.03,-8.119,-5.576,51.844,39.099,35.361,31.934,43.722,-5.576,43.664,-0.38,7.382,14.809,10.463,-5.576,-7.54,-7.54,-8.508,-0.38,56.056,-20.32,-8.508,-43.189,44.08,37.77,-35.745,20.708,-16.82,16.044,16.044,57.2,2.3,-14.175,54.134,-0.677,-16.25,1.5,-1.408,63.633,-3.613,-9.13,9.979,52.559,55.417,9.979,-7.981,54.756,15.255,-42.833,-7.54,32.884,12.17,2.32,-0.677,14.002,19.692,48.873,-7.242,60.485,32.884,60.485,31.934,-50.964,-25.37,-16.294,63.933,13.853,19.85,50.861,55.424,-0.162,-21.244,4.203,63.983,21.125,-6.102,-0.92,56.056,-16.829,19.514,30.793,-0.171,38.404,2.781,41.409,55.417,36.406,-6.312,27.881,32.884,-5.05,0,19.82,2.3,50.324,39.964,-7.54,-18.992,43.384,-36.868,20.546,4.203,56.653,33.086,14.002,-7.25,63.633,56.056,20.708,11.985,18.57,2.781,-0.171,-21.244,60.485,19.692,56.653,35.361,-7.942,-7.981,-1.408,0,39.284,-0.43,36.227,-1.408,-8.242,-8.119,12.702,42.063,54.134,37.748,-0.077,-15.787,-21.244,1.488,64.416,-6.77,13.434,-23.37,44.133,-7.93,-21.244,32.761,64.416,52.449,37.735,63.633,47.52,-8.119,19.03,19.85,32.884,13.33,-6.72,36.227,13.33,0.8,64.05,63.85,-4.271,5.203,-33.425,-41.33,0.029,14.809,18.13,-7.942,60.032,-37.406,38,-37.406,11.538,-39.28,-7.242,19.475,1.38,-38.82,31.22,54.049,1.22,38.654,55.417,-4.523,40.821,2.32,60.485,51.45,-37.52,32.884,54.135,36.406,14.473,4.203,37.748,52.559,51.844,54.049,-8.991,58.236,31.934,0.552,-7.2,51.79,12.606,-16.294,55.678,-37.52,51.79,-0.38,37.748,56.056,0.8,38.789,-6.52,49.57,37.125,1.22,63.983,38.404,-40.35,-1.697,16.55,63.633,-5.25,-5.05,13.793,61.299,-5.358,2.781,12.12,-22.4,-2.68,-1.467,-0.38,4.203,12.506,-7.54,-57.8,-23.37,30.793,-15.6,-6.77,31.771,54.596,19.421,-3.522,41.805,27.73,32.884,43.418,-4.271,-39.42,42.688,12.888,-39.3,0.686,-39.42,-21.244,-39.28,52.825,57.05,37.748,0,28.271,-21.244,54.65,13.257,-6.102,-8.058,-7.942,2.781,-22.33,1.22,10.025,-8.108,0.8,-39.637,-4.271,19.475,0.029,37.748,37.748,-16.68,13.257,44.08,7.691,-7.93,-35.223,44.674,34.724,35.361,-38.12,-7.54,13.813,14.809,10.83,-39.157,20.546,-39.42,-7.2,32.884,54.135,-39.42,4.892,-6.102,-41.33,60.485,19.421,37.1,63.933,12.702,39.099,37.748,55.972,14.501,1.112,-41.33,-5.576,0,50.148,60.485,36.227,53.256,50.267,7.644,-39.42,-19.15,-25.887,55.832,-16.25,-37.92,12.98,12.3,32.884,63.633,-7.54,14.382,-1.408,-3.613,34.724,-28.98,-4.08,37.748,32.884,-16.829,51.498,34.724,-39.157,15.32,-7.143,56.653,56.056,-21.244,-6.137,-4.649,-7.54,12.12,-39.42,-7.93,46.206,56.653,-23.37,-14.27,35.361,36.406,41.409,-16.25,36.618,46.2,0,63.633,19.475,38.537,40.821,-7.93,14.473,-8.058,52.103,19.421,28.271,38.789,-39.42,64.653,46.815,36.406,64.416,38.404,37.748,9.83,-39.42,52.559,54.049,36.406,-23.37,-16.829,52.559,46.206,-0.171,-7.242,31.934,24.285,-1.467,55.417,-6.102,-0.37,64.416,-16.294,12.423,10.025,63.633,-8.42,-39.3,-7.54,34.094,-0.077,-16.507,42.33,44.83,-2.764,53.75,-6.137,50.324,-4.523,11.58,-7.981,36.406,65.715,-0.37,31.22,-39.157,64.416,-5.525,43.844,31.888,-39.42,53.891,-7.2,-8.119,-0.38,-8.119,-35.745,-16.507,39.964,-6.102,19.03,-39.42,-44.7,-6.102,53.256,-58.445,-0.38,-0.677,40.656,0,-9.135,-1.408,-0.37,17.6,19.421,58.172,36.586,53.891,-5.358,-35.653,54.134,19.475,-39.157,36.921,65.033,63.416,58.13,-21.244,53.321,2.781,-5.05,31.934,37.735,11.538,39.099,31.934,36.406,11.538,-0.375,36.406,-7.942,-5.094,13.6,-8.119,12.769,-12.83,-8.53,-21.244,36.406,65.715,14.473,55.832,42.544,53.93,14.002,-42.833,55.972,-21.244,12.423],[-87.004,175.57,-60.652,14.999,-84.233,-70.85,-71.93,140.244,-17.316,14.999,174.07,112.308,140.303,140.677,-152.742,29.25,-19.083,-163.97,-86.539,-172.51,141.38,-103.62,-122.18,124.792,144.818,-17.516,-103.62,127.63,100.474,-84.233,151.33,110.88,138.523,-178.794,55.708,136.771,-169.944,138.523,160.82,140.877,-78.341,-20.883,-175.63,-68.391,-90.88,109.879,14.962,142.686,-175.63,-90.88,-72.496,150.88,-83.852,-156.25,14.999,158.836,141.481,14.962,14.999,-71.93,112.308,-83.852,-169.944,139.394,114.242,160.251,-95.2,-19.666,12.02,35.914,-61.165,-154.682,55.708,-61.33,139.394,-152.742,-156.25,110.446,-113.42,160.595,55.708,119.07,-177.168,145.037,109.992,100.474,-155.1,161.36,160.251,-88.269,-119.029,-177.92,138.523,-17.516,-89.633,-77.37,-71.409,-177.168,-24.35,115.375,125.447,138.528,-178.794,-8.155,-122.193,-95.2,109.879,-17.316,-19.122,125.491,139.394,93.858,138.528,160.02,-177.188,-19.083,-75.293,-86.84,-177.188,-20.266,119.07,112.922,-71.93,-93.228,-87.004,-171.252,177.18,-19.083,131.104,-17.516,112.308,175.57,-85.324,160.326,138.728,-78.436,-155.253,160.326,9.17,145.504,-73.585,100.474,-155.287,131.104,14.426,-155.87,-155.608,155.461,130.305,159.674,138.114,131.249,-121.813,14.999,155.461,-77.986,-71.183,124.737,112.308,123.132,151.33,-70.75,137.587,168.346,112.922,-19.083,-69.797,141.001,44.08,130.305,163.25,-21.416,120.993,139.759,-77.37,-158.17,14.999,140.799,109.879,-17.617,140.44,110.446,-25.32,131.104,138.523,130.305,160.642,159.647,-26.483,-155.87,175.632,-175.07,14.999,141.001,144.013,-178.006,-20.883,107.84,-71.586,-179.97,-61.664,-177.168,145.8,138.728,131.104,-61.18,154.808,-92.109,-156.25,-122.18,-90.88,14.999,-16.728,40.67,-155.608,-71.93,-15.58,127.33,140.88,139.394,55.708,98.392,-161.894,-179.97,176.5,100.681,-174.166,-71.93,155.246,120.993,160.595,145.845,-95.2,137.587,123.685,139.367,139.098,14.999,160.595,13.897,130.57,137.587,55.708,158.03,120.35,165.804,-165.986,165.804,173.9,127.33,112.922,131.104,160.642,127.33,14.426,-68.541,-78.341,-16.641,-61.341,-155.608,55.708,176,-91.17,-78.815,175.632,42.229,-76.4,175.632,42.229,123.57,-121.767,110.446,-70.568,-93.228,-8.155,40.67,139.394,-155.47,-70.903,175.57,-103.62,127.33,100.474,-17.516,-103.62,-86.165,29.2,-83.852,-179.97,-93.228,-26.67,-165.986,-17.316,-71.93,-17.516,130.862,-72.117,-103.62,114.242,131.104,-84.233,131.104,147.12,29.2,140.874,145.122,121.708,36.292,138.523,151.158,-20.883,-166.923,35.914,139.526,129.881,14.933,161.36,160.251,106.965,-83.767,109.879,101.264,-67.73,-87.004,-61.165,140.734,120.35,-91.17,-159.38,145.964,-76.4,140.049,-70.568,159.443,-72.646,-19.083,112.922,14.999,110.446,129.714,139.526,-85.622,-19.083,159.45,138.528,141.289,42.229,138.523,-70.903,124.865,-85.622,-85.324,139.021,131.249,-60.652,-161.894,96.821,125.37,-91.186,161.36,43.38,144.561,160.595,-24.35,124.737,-86.84,27.16,-165.986,130.657,131.39,157.328,-61.64,139.526,123.132,110.446,-24.35,29.2,102.615,167.47,175.632,-61.165,130.657,-98.622,127.33,41.83,-169.944,102.615,-101.75,-70.568,131.104,125.407,-152.742,-19.666,55.708,-71.93,-119.032,-19.666,-73.504,-17.516,114.242,140.281,96.821,131.104,131.104,131.104,-71.729,127.33,101.264,112.922,156.014,-155.1,-103.62,172.05,14.999,-19.083,136.771,131.104,112.95,-130,55.708,127.33,120.993,158.03,131.104,175.57,-19.083,124.792,-155.608,152.475,139.918,-122.18,-77.986,156.014,110.446,138.523,176.5,-152.742,-77.626,14.999,14.999,138.728,130.862,-161.894,153.2,140.44,110.446,-70.761,-16.641,120.993,-148.433,125.407,-90.601,130.862,-84.233,130.217,-77.656,140.839,42.229,-90.88,130.657,124.056,143.031,-91.17,141.38,128.08,-108.83,157.979,27.16,-71.729,107.6,100.474,-91.17,177.18,159.443,-152.251,129.144,14.999,-15.58,141.38,-78.436,138.528,137.587,144.561,139.27,-159.38,-88.269,160.642,130.657,101.264,-121.229,140.734,-88.269,-85.324,-67.73,-69.142,155.196,-8.155,-71.93,123.685,160.642,175.632,138.523,174.07,14.426,33.792,161.36,112.95,175.57,29.45,-88.269,0,-86.165,123.685,139.526,-61.18,110.446,-78.442,175.632,160.642,14.999,-16.728,-172.525,-91.186,175.632,155.461,139.394,43.38,-161.894,138.528,-69.797,141.289,129.926,-75.324,109.879,-69.832,41.83,-93.228,-89.63,112.308,139.394,-20.266,-108.83,73.513,9.17,125.447,138.523,55.708,153.25,14.999,55.708,130.57,117.77,-84.703,-75.33,157.339,-90.88,122.01,-101.75,160.2,-62.18,160.642,144.561,140.799,167.17,112.922,140.44,-71.183,-155.287,-175.42,-21.783,130.862,138.523,-97.27,160.595,36.57,-84.233,151.158,-93.228,114.242,-144.017,-19.666,-28.08,110.446,138.523,-90.601,155.225,129.926,139.394,161.36,-71.183,-71.93,-152.742,109.992,-61.664,139.963,138.523,167.5,-71.857,29.25,55.708,128.997,-85.324,55.708,161.36,144.818,-155.287,138.523,-98.622,161.36,130.217,110.446,100.474,139.766,120.35,-61.165,-77.656,155.196,-163.97,139.394,43.38,145.161,14.426,-91.17,141.38,-17.316,-101.75,110.446,130.862,-22.483,-178.146,-90.601,139.394,150.516,160.326,-22.083,148.42,-107.035,-171.252,-86.702,157.711,-60.652,160.595,110.446,124.737,-31.216,155.196,124.792,112.95,158.03,43.38,40.3,42.83,-61.165,-177.188,55.708,125.07,110.446,122.833,124.792,160.642,-158.17,-84.233,-17.516,-91.35,157.979,-103.62,138.728,42.229,-175.508,124.056,-71.729,-158.17,-69.797,-77.37,178.478,-77.68,36.33,-22.083,-121.49,156.978,123.685,155.461,158.03,-155.287,-77.68,-72.618,138.523,-22.566,138.523,55.708,-61.18,127.53,-25.47,175.632,-121.76,-86.702,-84.233,-155.608,155.246,0,-78.436,154.808,165.5,110.446,-84.703,-71.93,160.642,144.013,123.132,-78.598,140.072,-60.652,-155.608,161.36,100.474,-75.324,138.728,-27.57,160.642,-179.97,14.962,55.708,-121.767,125.447,123.505,156.014,-67.73,-122.193,-159.38,43.38,-91.55,-175.07,140.757,160.326,168.346,148.42,-17.516,-83.767,-155.608,129.714,122.775,-155.608,45.992,130.57,-19.083,-177.188,151.33,120.993,-152.742,-72.445,-77.656,157.718,141.166,55.708,-71.378,109.208,145.037,-101.75,-71.729,-77.37,145.67,-89.633,158.03,138.523,-70.903,105.423,-71.349,157.979,148.019,141.166,145.964,-90.88,-61.165,158.05,-19.083,-97.27,158.07,-155.27,148.42,-61.64,116.47,-72.578,55.708,161.36,-89.633,-153.43,138.523,121.191,-121.508,-91.408,-86.539,-97.27,-87.004,160.326,-156.25,138.728,-71.729,-121.688,-19.083,160.326,110.446,177.18,-83.852,175.57,153.2,-97.27,158.03,0,127.33,-78.183,140.677,108.408,-17.316,-86.84,176.5,-177.188,-88.269,121.601,-121.49,176,140.244,125.185,-19.083,161.36,55.708,-72.445,-153.43,109.208,140.44,177.18,55.708,131.104,131.104,124.792,124.892,112.922,-155.1,131.104,-78.436,112.922,100.474,-169.944,140.44,148.42,158.836,96.821,14.999,124.737,139.376,0,-170.629,-86.165,-25.88,150.027,107.73,-17.516,-175.07,0,14.426,145.57,144.013,112.95,130.862,-78.436,131.104,14.999,109.208,114.242,160.251,55.708,-19.666,150.516,-152.742,158.196,113.341,-175.016,-71.93,138.523,96.289,-71.729,-152.742,131.249,151.33,138.523,161.36,160.326,125.407,124.737,158.03,-90.88,-121.554,-174.87,-78.598,124.507,129.714,-175.65,93.858,44.3,0,-17.516,-61.165,-86.84,-15.58,96.821,-168.13,175.632,-71.93,112.95,-135.75,122.775,14.999,-155.608,-99.13,-19.666,-78.598,139.766,160.642,-121.76,109.879,14.426,159.443,146.994,-155.287,131.104,138.728,-61.165,39.93,156.753,-25.78,141.001,131.104,131.104,-84.233,157.718,140.244,-156.25,-155.1,14.999,-163.97,126.53,-17.316,160.595,-16.641,-175.382,-71.378,131.249,-16.647,41.809,-19.083,14.426,127.53,158.836,129.881,114.056,-159.38,159.82,14.999,-165.986,119.07,138.036,106.965,120.993,138.728,157.47,113.341,129.881,-163.97,138.728,141.38,-169.944,-72.618,101.264,-62.8,-169.944,139.153,160.326,175.57,0,-71.409,14.999,-164.65,161.36,139.759,-98.622,-103.62,112.922,139.394,141.001,-61.165,138.114,131.104,165.804,-27.32,-152.742,139.394,168.12,-93.228,158.836,109.992,127.33,0,-115.616,160.642,160.595,-19.083,131.104,-78.436,112.95,14.999,168.12,-156.51,-25.47,112.95,103.121,-19.083,112.922,112.922,-71.93,148.42,-89.633,-76.4,-61.165,144.561,123.258,-172.525,130.862,-72.07,160.642,130.217,-119.029,155.461,-71.93,35.447,-155.608,-122.18,14.999,29.2,-25.67,-84.703,14.426,145.037,14.999,29.485,14.426,116.47,167.17,-152.742,14.139,-97.27,-155.287,156.52,-165.986,141.38,131.104,153.2,-19.633,14.999,14.999,168.12,-179.97,-19.666,142.686,115.375,168.12,-16.783,43.38,-71.729,26.47,116.47,109.208,100.474,-71.378,158.05,-152.742,159.15,138.528,168.12,165.804,159.674,174.07,-22.483,-16.641,145.964,-67.73,-72.496,140.877,42.229,125.37,-71.93,175.632,144.893,15.213,35.914,160.533,112.95,112.922,-121.229,141.289,-83.852,-178.146,160.703,140.88,145.161,160.642,-19.122,-155.608,-22.083,-72.496,130.305,139.394,137.587,112.95,177.18,137.48,-78.436,-113.35,-89.633,-61.664,175.632,-99.13,-98.622,-144.017,140.049,55.708,14.426,155.196,123.685,-90.601,-121.813,155.246,-20.666,176.5,-61.165,-122.193,139.394,160.251,124.792,-17.316,-71.586,-165.986,-72.794,-140.25,145.964,-179.97,-24.35,14.962,112.922,139.526,39.93,129.881,176.5,130.657,-98.032,175.632,140.281,138.523,55.708,-90.601,125.407,148.42,-86.84,147.35,-86.165,-71.857,-84.703,109.992,-84.703,-161.894,55.708,130.57,-25.32,0,-62.18,-117.45,151.33,140.281,-141.75,112.922,138.528,-86.539,-70.568,141.38,140.88,-86.539,-19.7,32.75,-72.445,-71.729,-19.083,148.42,175.632,141.001,155.461,159.443,-158.17,14.962,161.36,-166.923,168.12,-161.894,109.992,145.1,14.426,175.57,-90.88,-78.436,130.217,14.999,-130,-77.37,101.264,140.788,112.95,-119.029,-91.55,-165.986,136.771,-90.88,43.38,-27.32,123.685,176,-90.88,-19.083,-16.817,175.632,-78.442,168.12,123.685,154.808,125.447,-68.55,167.17,160.642,-113.35,151.33,-71.93,-155.287,101.264,119.07,-77.656,-67.765,160.642,-86.84,55.708,14.426,160.642,42.229,140.049,-177.188,130.862,141.001,139.759,55.708,-177.188,-77.986,-78.442,-130,-16.641,100.474,-85.153,-19.666,110.446,-86.84,160.595,125.407,175.57,142.686,113.341,175.57,-119.029,139.766,-21.416,-91.408,43.38,-25.78,-175.382,-86.165,109.208,130.862,55.708,-121.554,-161.894,-86.32,-72.027,25.396,24.439,-103.62,174.07,-87.004,157.339,110.446,-25.78,179.58,-71.93,105.423,-121.76,-72.97,138.523,141.38,123.685,-91.186,-16.641,158.196,175.632,123.132,149.07,158.836,-104.3,131.104,-165.986,15.213,159.443,-152.742,138.523,159.443,113.341,-159.38,127.63,140.799,-153.43,137.587,109.992,160.642,170.28,168.346,-78.436,145.83,109.879,160.595,168.12,14.962,-122.12,-75.33,-17.83,14.999,140.244,160.2,151.33,55.708,-130.55,131.104,-71.729,139.918,-155.287,158.03,14.426,175.57,-161.894,145.964,-155.287,139.566,161.36,147.131,-89.633,2.97,138.523,-98.622,139.394,157.979,-152.742,139.394,158.836,-19.083,130.657,109.992,138.523,-165.986,-78.436,177.18,175.632,14.999,14.426,2.97,-60.652,110.446,141.289,-26.533,-78.436,131.104,112.922,-88.269,-61.165,-172.525,177.18,131.104,159.443,-85.622,-99.13,110.44,160.87,46.7,100.681,-155.361,144.013,-152.742,141.289,36.57,-78.598,-95.2,-98.032,160.595,176.5,-144.017,-177.188,131.104,171.32,-69.797,-155.87,-105.43,158.836,160.595,130.305,112.308,-175.07,107.73,99.021,156.014,-86.702,158.196,-71.729,131.104,14.999,-91.35,-99.13,130.57,161.36,138.728,55.708,35.914,-89.633,110.446,-173.75,-155.287,-169.944,-27.32,137.554,160.642,-73.504,-71.378,125.37,55.708,148.42,-177.188,-155.47,140.677,-72.117,-103.62,144.893,-72.578,139.918,138.523,123.685,112.308,55.708,55.708,40.3,-121.49,-69.5,103.121,-91.55,123.132,-19.083,-148.525,-136,110.446,-72.97,155.461,-17.316,-77.656,122.455,103.121,141.38,-77.37,142.686,168.37,-71.729,125.407,143.47,-17.316,126.53,-17.118,-75.365,140.757,-23,-86.702,-155.608,14.999,-71.93,157.12,-76.03,110.446,-91.408,138.523,131.104,139.394,-78.598,160.595,-77.986,125.07,9.17,14.999,160.642,130.862,131.104,-78.436,127.33,-86.84,14.999,-156.25,14.999,-77.37,-69.092,131.104,-175.07,130.862,130.862,138.523,-70.903,-175.63,-178.794,140.812,100.474,109.992,-17.516,-70.568,-177.92,-86.165,146.252,129.714,-62.18,-19.633,-61.165,55.708,141.481,-86.165,161.36,-86.539,-91.186,-60.652,-70.372,-159.38,-77.986,-104.3,139.602,160.326,-19.666,13.897,-71.93,-76.4,130.305,-71.586,160.642,139.526,107.6,-69.797,131.104,158.196,-175.508,-88.269,100.681,14.999,-75.324,160.642,100.474,-121.767,-84.233,-25.78,124.737,-129.27,127.4,13.897,130.657,131.104,101.264,109.879,-17.316,-119.029,14.999,-152.742,-165.986,-98.622,130.862,-153.09,14.999,138.523,14.139,-16.666,140.874,176.08,-163.97,138.523,110.446,-71.93,110.446,139.526,-78.436,-69.092,107.6,-27.32,101.728,122.775,-104.3,-89.633,-90.88,139.394,-61.305,138.523,-71.93,-19.666,14.999,0,121.708,-86.15,130.57,176.5,139.394,125.407,156.875,138.728,141.289,-78.442,112.922,-155.608,-121.229,122.01,-165.986,119.07,-174.317,-89.633,159.674,158.836,105.423,125.407,155.246,-16.641,175.632,175.57,-129.1,-90.88,55.708,160.642,130.862,169.238,-179.97,-161.894,155.62,112.95,-76.4,-165.986,141.166,-78.436,175.57,-71.93,-19.666,113.341,14.139,-164.43,139.766,-19.666,138.523,-166.923,-25.47,141.001,144.893,158.196,159.674,121.708,-71.93,168.536,-158.17,-23.783,177.18,25.396,-121.82,154.808,112.922,-90.88,-72.496,113.341,115.375,-14.37,-78.436,158.196,161.36,128.223,100.474,36.57,141.289,106.965,161.36,112.95,-121.695,158.385,-17.316,160.595,-71.93,123.258,129.881,158.03,-89.633,159.443,40.67,14.999,-87.004,167.5,-69.895,41.809,159.443,-175.42,-92.109,138.523,-61.33,14.139,-61.18,138.036,-71.378,-175.63,-78.436,-152.742,14.999,130.57,138.523,155.461,-73.4,100.681,140.757,-155.608,-83.852,124.737,107.6,119.07,131.104,138.528,177.18,-169.058,-119.029,-110.67,29.2,14.999,-155.287,-152.742,-103.62,160.27,43.38,-72.618,138.523,-13.63,-175.55,130.217,124.056,-78.442,-68.83,-71.586,120.993,-16.783,139.526,14.426,-99.13,140.44,-103.62,165.804,-83.852,110.446,150.871,112.95,110.446,-98.622,123.685,158.03,-163.97,153.02,-71.729,-61.165,-90.601,-113.5,14.999,-91.408,-169.944,160.326,130.862,161.36,100.331,55.708,121.191,-161.894,140.757,119.07,174.07,96.289,-67.73,140.44,124.792,-165.986,160.326,121.641,14.139,-98.622,160.642,-78.436,157.572,-69.797,147.12,-75.324,-75.324,139.394,-23.783,154.808,147.871,14.999,-71.729,-135.75,140.303,140.839,-86.84,-172.51,55.708,125.37,-91.552,-119.03,-17.316,142.686,145.037,160.595,159.443,-19.083,-161.894,35.914,175.57,124.865,-113.5,-70.568,-152.411,-19.083,-86.84,55.708,99.539,-78.598,-155.287,177.18,130.57,-71.93,130.862,150.094,130.862,138.528,14.999,-73.75,-8.155,43.874,158.196,29.2,110.446,130.862,143.47,-90.88,123.132,138.528,-16.728,103.121,35.914,113.341,-178.794,168.12,160.642,-86.84,123.505,14.999,150.516,-156.25,150.516,122.775,-129.58,154.508,-155.253,123.685,8.762,121.708,-91.17,-152.742,-86.702,-19.7,55.708,121.641,130.657,131.249,-122.18,-71.75,-60.652,-61.165,-96.75,-99.758,-71.52,-71.93,157.979,145.8,160.642,145.037,14.999,151.33,14.999,-155.287,26.47,-87.004,140.874,-155.87,14.962,128.849,150.871,142.854,-61.18,112.922,115.375,103.121,-152.742,175.632,158.03,-155.608,-91.55,139.394,123.132,175.57,-69.5,-17.516,14.426,-165.986,-76.936,165.804,140.788,-153.43,-16.641,127.33,55.708,-19.083,-152.742,-72.117,-90.601,130.862,-121.229,-71.58,-84.703,-78.436,125.447,151.786,-161.894,101.264,124.056,55.708,151.33,127.33,100.681,36.57,157.718,-156.25,130.862,-155.608,139.394,14.962,-72.81,125.407,98.392,140.799,14.999,129.881,112.95,-155.608,119.07,123.685,106.965,14.139,109.208,175.57,36.446,-16.641,112.95,-113.206,161.36,101.264,14.999,101.264,-72.646,102.615,-91.55,139.766,-19.666,-168.693,100.474,123.132,-78.442,159.443,145.037,-84.233,121.708,141.16,148.115,127.33,-156.25,130.299,-86.702,161.36,154.182,-179.97,-155.608,-78.815,-174.166,107.6,-175.63,175.632,-71.93,-78.598,-91.17,138.523,137.587,-86.688,129.926,-155.253,-78.364,-69.895,176.33,141.289,110.446,-61.165,160.595,138.036,-165.986,-175.382,-17.316,-159.38,116.47,168.12,-78.442,107.84,-68.53,-156.25,160.642,129.714,55.708,-177.188,130.299,-17.516,125.491,-86.702,112.922,-179.97,0,157.979,139.367,-86.165,-90.77,145.1,138.528,-70.568,-71.729,-87.004,-155.287,-86.702,55.708,-68.83,112.922,100.474,-86.165,-155.287,158.03,100.474,131.104,-19.083,-91.12,131.104,-177.92,100.681,-86.702,-156.99,13.897,0,-61.664,-89.633,-71.93,103.121,100.474,158.07,139.394,120.993,103.121,140.049,-22.483,-172.525,131.104,55.708,-17.617,158.836,124.056,168.12,128.08,29.2,141.38,-85.622,139.526,-103.62,-78.815,-177.92,-16.641,-122.18,141.38,-71.93,12.02,113.341,-19.083,152.12,-177.92,-121.93,55.708,-70.903,113.341,158.03,144.427,14.962,-103.62,0,107.6,142.686,153.2,-73.4,55.708,-95.2,14.999,127.33,139.526,139.394,124.056,123.685,-155.87,-16.666,-85.622,-155.287,-97.27,-130.63,-21.416,14.999,168.12,160.326,130.57,-168.03,-16.783,-161.894,-84.703,-168.03,110.446,156.753,111.192,-86.84,-70.903,174.07,138.528,145.733,138.523,55.708,112.922,-155.87,-16.641,118,141.38,167.835,55.708,14.426,158.03,-78.598,-148.525,-165.986,73.513,14.139,103.121,-152.742,112.922,25.396,55.708,120.993,-98.622,159.443,155.196,-88.269,-90.876,-155.608,2.97,14.999,140.281,112.922,137.587,-121.113,145.8,-75.324,-90.601,127.894,131.104,158.05,-19.666,139.394,155.196,152.12,107.6,-119.029,-88.269,-17.516,109.208,-78.341,-91.35,161.36,-23,14.999,127.33,158.836,130.217,139.098,-104.3,157.407,-19.122,-71.729,139.766,-19.083,141.001,-103.62,-152.742,-103.62,-161.894,-103.62,27.16,-77.986,158.196,-25.67,-19.666,105.423,-70.568,101.264,156.014,-71.857,-140.25,160.595,131.104,127.33,55.708,-155.092,55.708,-174.317,-159.38,-72.496,130.862,130.017,-76.4,-19.083,125.447,161.36,-84.233,55.708,174.07,-71.52,29.485,-104.3,-89.633,-71.729,-61.165,167.17,14.999,112.308,-155.287,-89.633,140.44,-87.004,140.677,150.083,138.528,101.264,155.196,115.375,168.12,-93.228,138.523,179.58,-177.168,145.964,-78.436,138.036,124.42,125.407,125.407,-71.93,-71.93,-130,105.423,-72.618,-174.166,-18.03,14.999,-84.233,-22.566,-177.168,-38.08,-98.622,14.999,-98.622,125.407,-89.633,-71.378,-86.165,55.708,160.642,-163.149,-148.586,138.523,-172.51,-103.62,-72.618,14.999,175.632,-87.004,139.526,-90.88,159.443,160.642,141.102,125.407,130.862,158.836,138.523,-77.37,168.346,-89.633,101.264,29.2,127.33,-179.97,112.308,138.523,-169.944,-90.77,-25.67,-152.742,105.423,-71.502,140.44,-77.986,-71.729,160.595,-19.666,-91.519,167.17,130.305,-177.168,167.5,109.208,151.33,0,-155.287,-75.365,140.244,138.523,-156.25,112.95,-122.193,-166.923,148.42,103.121,-17.83,-19.666,160.326,157.979,130.862,-82.543,176,-103.62,-22.083,-121.813,-155.608,-78.436,123.258,100.474,168.12,0,-88.269,176.5,160.326,-155.287,-61.165,139.766,-28.08,-71.93,-25.67,167.17,-72.15,-89.633,140.799,55.708,14.999,174.07,110.446,29.2,157.979,14.999,156.753,120.993,43.38,29.2,-164.43,-71.645,-19.083,13.897,-85.324,-85.324,-156.25,-25.78,141.38,-155.287,-19.083,158.836,-71.729,127.33,-77.986,139.394,-85.324,44.3,-148.586,-72.646,120.35,-25.47,-155.608,151.33,-19.083,138.036,-72.618,-90.88,-61.165,-177.92,157.572,-126.78,-17.316,14.999,158.196,-15.58,140.049,-25.47,-113.5,-98.622,165.804,131.249,-155.608,145.037,130.87,160.32,-61.165,-86.702,125.407,-91.408,-179.97,160.326,55.708,14.999,-152.742,160.595,145.161,175.57,55.708,-23.783,-122.18,-70.595,14.999,-156.51,122.775,130.657,-87.004,-158.17,113.341,-17.316,-165.986,-78.341,-104.3,-77.986,174.07,38.78,114.056,140.303,175.632,-19.666,140.303,14.999,45.497,0,-89.63,-86.165,161.36,138.523,29.2,-152.742,-20.666,-72.431,-98.622,139.394,123.132,113.341,174.07,-61.165,175.632,-68.391,-25.78,151.33,-161.894,160.642,139.394,145.8,127.33,-85.324,138.728,-69.895,-155.287,-19.083,36.33,137.587,-84.233,138.523,0,-17.516,161.36,105.423,160.32,160.326,109.879,138.728,-78.436,105.423,-71.645,-26.67,-91.519,14.999,-130.3,136.771,-71.378,141.001,35.914,105.423,153.2,-89.633,154.808,160.326,124.737,145.037,-140.25,121.708,34.621,168.12,-86.702,-16.728,-89.294,124.737,141.284,152.8,-19.083,-104.3,-84.233,-84.233,-61.165,-177.92,156.014,-19.083,-174.87,145.037,145.122,114.056,160.53,-174.87,-78.341,-163.97,-71.93,109.879,138.523,-78.141,121.708,110.446,161.36,140.799,144.818,-61.165,114.056,156.629,43.38,-19.083,-25.78,-16.728,105.423,131.104,151.33,120.993,114.056,158.836,-121.813,177.98,158.03,-89.633,6.85,-155.287,176.5,-86.539,130.657,152.203,124.507,150.027,127.33,112.922,-71.722,-75.293,-98.622,113.341,-165.986,-177.168,140.244,-121.554,158.196,-78.436,113.341,112.95,124.792,160.27,-86.342,15.213,-69.895,130.862,123.505,-67.73,114.056,-19.666,-86.84,-78.436,155.461,-165.986,-77.986,100.474,127.33,165.804,46.12,141.38,-85.324,112.922,-17.83,-72.15,-155.287,-155.287,123.685,55.708,-67.73,158.836,-19.083,-16.783,-152.411,168.346,157.718,112.95,153.93,14.999,29.2,73.513,-172.51,152.475,131.104,-84.233,157.979,-84.233,154.808,160.27,155.565,-69.797,29.25,-16.641,-175.07,-71.729,26.47,130.017,131.104,123.685,124.892,-155.287,-159.38,151.33,-69.5,140.244,-28.73,125.407,101.264,161.36,2.97,-88.269,175.57,0,100.474,160.27,-174.166,160.642,138.523,112.95,-156.25,-71.93,-61.18,125.447,109.208,-86.702,120.993,140.839,-17.83,145.964,138.523,160.595,-165.986,131.249,-75.324,14.999,123.685,125.407,175.57,-71.93,112.575,105.423,-68.83,-156.25,160.32,116.47,109.208,0,-129.27,-153.09,55.708,-72.117,14.999,-85.324,55.708,158.836,161.36,-78.436,138.523,-86.84,123.685,-19.083,175.632,139.021,14.399,-78.598,159.674,-155.287,100.474,14.426,153.48,137.554,55.708,152.203,-168.13,144.427,140.44,-71.93,-155.361,131.104,-61.64,-170.629,-152.251,159.443,-155.287,-78.436,105.423,124.792,-121.113,145.964,-16.728,126.53,-159.38,138.728,159.15,-90.88,107.84,-153.09,105.423,-72.97,-21.783,161.36,-57.93,156.978,110.446,161.36,-163.97,-71.93,140.874,175.632,-19.666,139.021,168.536,29.25,-72.618,-82.543,122.775,157.979,-71.729,-86.84,-121.767,-122.18,100.681,-19.083,140.44,25.396,124.737,-155.287,-177.188,42.229,125.37,29.25,-98.622,175.57,-89.633,123.685,-131.28,120.993,138.528,-103.62,158.836,157.407,-152.742,159.443,141.38,139.27,176,138.523,141.289,145.8,-16.728,-122.18,152.203,-72.117,0,35.914,-90.88,-103.58,-83.767,-71.729,-16.728,112.308,-72.117,175.632,131.104,-161.894,-121.82,139.766,14.999,-168.13,140.799,141.289,140.051,-113.206,160.595,36.446,-77.656,112.95,112.95,-17.516,15.213,123.132,157.572,159.804,175.57,175.632,119.07,-22.083,14.999,-19.083,-19.633,-72.618,-103.62,106.965,-19.083,130.862,-104.508,146.252,-78.436,147.12,108.408,-155.608,124.737,137.59,120.993,14.426,145.03,155.565,-163.97,140.677,114.056,140.244,149.075,165.804,-163.97,-73.48,139.394,136.771,156.753,131.104,37.583,-78.598,168.12,137.587,158.196,-155.608,-84.233,-19.083,131.104,-90.601,158.03,127.33,55.708,-122.18,14.999,-169.944,152.203,72.6,154.508,-73.585,-22.566,0,160.251,-75.33,14.999,158.836,-169.944,-89.633,-130,-130,112.922,130.217,14.999,139.602,120.98,-78.436,-21.416,120.993,0,-122.18,138.728,95.658,-174.65,140.303,-78.442,-27.225,-175.382,139.394,93.858,-93.228,13.897,-20.883,-155.287,154.182,122.775,160.251,-71.93,-61.18,160.326,-152.742,14.999,123.585,-121.229,-172.51,148.838,131.104,14.999,-77.656,-25.88,129.714,-19.666,168.12,-84.233,110.446,151.33,109.879,113.341,131.104,157.718,-87.004,-77.37,130.862,174.07,-71.93,-85.622,112.95,-122.18,-71.183,100.474,159.443,110.446,123.685,115.375,-155.287,138.523,168.346,160.642,14.999,163.25,33.668,-77.986,-21.416,159.443,105.423,-86.84,29.2,160.326,144.561,148.115,140.303,131.104,-71.183,-19.083,41.7,137.587,-168.13,131.104,130.862,-68.53,-99.13,0,-161.894,-103.62,29.25,161.36,14.999,118,141.38,-22.566,165.804,-71.93,-98.622,-179.97,127.53,55.708,139.394,129.714,157.328,-155.27,-17.516,-20.883,-67.73,35.914,157.979,-71.729,-103.62,-85.324,177.18,160.595,-86.165,-155.608,-152.742,107.6,-17.316,-152.742,124.792,158.196,112.95,106.965,-98.622,161.36,103.121,-179.97,130.862,130.217,-169.058,-19.666,-89.633,-105.93,55.708,160.326,119.07,29.25,14.999,101.264,-61.664,120.993,140.799,123.685,39.78,-70.903,-155.87,-89.294,-172.525,-83.852,-86.539,124.792,-72.117,139.526,138.528,0,138.036,140.799,-61.165,161.36,157.572,137.59,-60.652,131.104,159.15,123.685,160.27,110.446,127.33,130.657,-166.923,110.446,112.308,-99.758,105.423,141.289,-148.821,-172.51,175.632,-72.618,-23.783,-112.67,124.737,-61.664,150.516,-90.876,157.203,139.766,167.47,-164.65,-88.269,139.394,-103.62,-71.93,158.03,-159.38,-63.23,-152.742,113.341,-25.78,-163.97,-71.93,160.642,-103.62,155.461,139.526,-73.4,-23.783,-90.88,-19.083,29.25,-19.083,35.914,130.57,-86.84,14.139,-77.986,127.33,138.528,43.38,15.213,-103.62,175.57,130.862,29.25,131.104,-90.88,-90.601,43.38,-71.93,158.836,-175.13,-75.363,-78.436,14.999,-161.894,108.058,161.36,14.139,138.523,124.535,-70.761,141.102,140.877,158.03,-16.641,160.27,-121.841,-179.97,112.308,141.38,43.38,55.708,14.426,121.641,-86.15,-16.641,125.447,-140.25,148.42,117.77,120.52,138.728,124.737,-155.608,160.595,160.65,142.686,-90.601,-26.533,148.15,160.326,127.4,-61.165,177.18,160.08,123.57,129.714,158.196,146.252,159.45,-97.27,-75.365,116.47,-103.62,-110.67,158.05,-87.004,137.587,45.74,13.897,-72.445,-153.43,174.07,160.595,141.001,121.94,-78.436,-19.666,127.33,139.394,167.17,125.37,110.446,140.799,138.528,160.642,125.407,-69.142,176.5,128.223,-168.03,130.657,-90.601,-23.783,145.67,123.685,167.835,175.632,-155.287,130.862,160.326,55.708,151.95,-75.324,138.523,-98.032,43.38,14.426,-67.73,160.326,131.104,120.52,142.686,-20.883,106.73,140.877,132.622,-89.053,103.121,147.12,-71.93,96.289,-71.93,-121.508,147.12,124.792,176.25,14.426,-16.641,-90.88,140.072,160.326,123.132,-19.666,112.922,-62.18,157.979,130.017,-119.03,-19.666,-16.817,161.36,14.962,-155.608,142.686,-91.55,168.12,160.27,-172.51,-86.165,160.32,-89.633,158.03,-128.9,127.33,168.346,129.714,160.642,131.104,-78.436,-85.622,120.993,160.27,14.426,175.57,140.757,-91.55,-24.35,124.13,120.993,-155.287,130.305,36.33,115.375,-84.233,-72.97,2.97,107.84,160.642,139.526,-73.504,138.523,-179.97,-155.87,-179.97,14.962,106.73,139.394,130.299,124.792,158.196,-21.416,144.013,-78.25,102.615,100.474,-84.233,123.132,-91.17,110.446,-156.25,55.708,93.858,14.999,-75.33,-179.97,114.056,140.839,145.161,145.8,124.792,153.2,100.474,-71.729,-165.986,130.299,159.443,-121.813,145.8,-83.767,141.289,131.104,-19.7,12.7,-156.25,-129.58,141.289,-77.656,109.208,-78.436,-166.923,-71.93,151.33,-175.63,-170.7,112.922,-71.378,124.792,-177.92,-91.186,55.708,105.423,130.862,-155.608,45.17,-71.93,-77.656,-77.37,169.447,141.38,138.523,-88.269,144.818,112.95,-19.083,125.407,140.072,-19.083,168.346,14.999,159.45,124.673,175.57,159.443,155.461,138.523,55.708,151.33,137.587,-71.93,158.196,-72.97,145.122,138.728,-71.729,157.572,123.685,139.918,160.595,160.32,145.67,129.144,100.474,145.57,167.835,140.303,-122.18,124.507,160.642,29.25,-154.028,99.95,-86.84,-155.87,107.6,-175.65,125.185,145.037,138.523,-86.84,157.339,-78.436,161.36,-71.93,-61.64,125.447,145.037,55.708,175.57,168.346,160.642,14.139,-86.165,-16.728,-21.416,-78.598,8.762,-19.083,160.509,-61.64,-89.633,-19.083,107.6,130.657,13.897,114.056,55.708,157.979,-78.598,-152.742,100.474,-91.55,138.523,-155.608,158.385,14.426,123.57,148.019,159.443,138.728,-88.269,-121.76,-175.13,55.708,110.446,-103.62,155.196,140.44,-164.65,-99.13,114.056,43.38,-19.666,-103.62,-17.316,-93.228,100.474,55.708,-19.083,12.02,140.44,-72.618,137.587,158.836,168.346,-85.622,141.166,154.808,-16.817,-88.269,-71.93,140.049,131.104,14.933,-122.18,131.249,176,154.508,129.881,-155.608,-155.287,-71.722,-89.63,-103.62,124.792,-19.083,130.862,-72.496,14.962,-98.622,144.013,-71.729,55.708,157.718,130.657,112.95,-78.436,160.642,107.84,138.851,96.289,-153.43,-19.666,-91.546,147.35,-19.083,160.326,147.871,157.979,151.33,-5.22,139.098,-72.618,176.5,9.17,-163.97,-19.083,161.36,174.07,42.18,-19.083,175.57,168.12,-16.647,176.5,160.595,124.792,110.446,159.674,-156.25,167.5,-99.42,0,36.6,-17.83,-69.797,107.84,130.87,-84.233,177.18,167.835,110.446,100.474,145.8,167.17,144.013,107.6,-91.35,145.037,-19.083,121.94,-101.75,138.523,-70.903,-84.233,-174.775,37.88,160.595,158.03,-78.598,-83.767,115.508,159.674,128.675,-89.633,125.218,-71.93,-75.33,-17.166,116.47,-113.42,55.708,140.839,-12.28,15.213,158.196,-168.03,-130,-86.84,43.874,158.03,-72.618,-71.93,144.427,55.708,-77.656,55.708,-90.88,130.862,-158.17,123.505,160.326,160.595,160.642,12.02,138.523,161.36,14.999,130.017,138.523,-84.703,-71.349,-84.233,138.728,-163.97,112.922,14.426,14.999,129.881,157.572,-78.436,-75.293,121.926,36.75,142.686,-155.287,124.13,-22.483,108.058,-17.516,35.914,159.443,142.854,161.36,161.36,-71.857,176.5,140.677,112.922,157.718,160.326,-71.409,36.23,123.57,-78.436,130.862,-71.93,158.196,140.44,-104.3,-90.88,-90.88,138.728,-61.64,-61.05,45.17,144.893,-178.146,-163.97,-103.62,-178.794,-78.598,-103.62,160.595,-156.25,131.104,-103.62,-175.63,138.523,-159.38,-90.601,140.877,160.642,114.056,138.728,-76.03,102.615,123.57,141.001,-16.647,158.836,-86.84,-71.729,144.013,-70.903,14.999,140.734,140.44,142.5,-70.568,130.217,175.632,160.595,-17.316,140.44,129.881,175.57,140.303,-168.13,105.423,-155.287,118,-72.117,-98.622,147.871,43.38,175.632,-86.32,-103.62,176,109.208,112.922,127.4,-24.35,-179.97,-71.349,157.979,-84.233,129.714,-178.146,-156.25,29.25,-88.269,-172.525,123.685,139.021,-77.656,14.999,-71.409,-171.252,-71.93,36.446,138.728,159.97,130.57,139.394,-86.32,-84.233,-71.729,139.526,-176.13,-19.083,139.73,-166.923,-71.729,-78.442,-76.4,-86.165,-71.93,160.642,138.523,130.657,176.5,176.5,0,125.185,138.036,102.615,43.38,125.407,-155.608,-78.436,42.229,105.423,9.17,14.962,35.914,-85.622,-17.166,-168.693,-71.183,113.341,-67.73,-98.622,-77.986,-31.216,127.33,-16.641,107.6,159.674,-72.618,-161.894,123.685,-61.18,156.014,-69.797,-84.703,141.38,130.217,114.056,-101.75,153.48,105.423,142.686,145.037,-71.93,35.914,14.999,-171.252,151.33,-75.324,125.407,176.5,9.17,-85.324,-113.5,-98.622,-16.783,-89.633,-155.608,-19.666,-176.13,143.47,-89.633,-86.165,100.474,100.474,-61.664,-165.986,-78.436,160.27,-78.436,-17.316,-88.269,-104.3,-155.87,130.299,0,139.021,-78.598,145.8,14.962,-155.287,-172.525,-78.436,160.595,123.685,139.394,-17.316,-165.986,139.394,14.999,138.523,139.963,137.587,-70.568,120.993,-155.287,-122.18,139.394,-69.142,169.447,138.523,29.2,14.999,-91.17,-72.618,158.712,-68.246,130.305,131.104,160.642,25.396,14.999,0,-155.287,-89.053,-78.436,113.341,-19.666,-19.666,158.196,123.132,-19.083,-89.633,14.999,-72.618,-19.122,150.516,-161.894,-174.317,-155.287,-90.601,-69.142,153.2,109.879,175.57,-89.633,-177.168,9.17,-21.783,114.056,122.202,-121.76,115.375,-77.656,100.474,139.491,144.013,174.07,-82.543,177.602,14.962,112.922,-76.4,35.914,160.595,145.8,131.39,138.523,139.394,107.6,122.775,175.632,161.36,-153.43,121.94,-25.32,157.407,131.104,109.014,140.757,-26.67,113.341,142.5,122.833,-19.666,168.12,144.893,-19.666,-166.923,14.962,-92.109,112.95,55.708,-155.287,-78.364,-121.554,-75.33,-75.293,112.922,112.922,175.57,136.771,-22.083,110.446,157.718,121.82,14.139,138.523,-85.622,-25.78,-17.316,176.5,-22.566,-153.43,112.308,171.32,130.657,151.33,-72.618,-175.42,-17.83,122.775,-78.436,161.36,-126.78,-155.287,-69.797,-83.852,160.642,140.303,123.57,-155.608,-17.316,-155.608,-130.63,-72.117,131.104,-155.608,-86.165,-69.241,155.196,130.862,131.104,-88.269,123.685,29.25,140.854,138.528,124.865,-19.083,140.44,-28.73,43.38,-166.923,-161.894,-77.656,-91.55,-155.287,-90.601,150.516,103.121,114.056,152.203,130.862,148.838,-98.622,-90.88,177.18,-121.767,-121.113,114.056,-103.62,-71.409,158.836,-179.97,-22.566,106.73,141.289,-155.287,103.121,-163.97,14.999,140.44,158.03,-90.88,-16.666,130.305,109.208,-71.93,150.871,-71.93,-122.193,123.685,161.36,131.104,-122.193,-70.903,160.27,141.38,129.144,55.708,174.07,153.25,-23.783,0,-163.97,-117.46,73.513,136.771,-161.894,-19.083,140.44,-70.903,153.2,144.893,157.979,41.83,139.394,-122.18,124.737,73.513,55.708,109.879,55.708,-84.703,161.36,-91.35,35.914,-17.316,-84.703,-78.598,14.999,-70.492,42.442,14.426,153.2,-121.49,129.881,124.865,105.423,116.47,127.33,101.264,138.32,145.037,-75.324,14.999,109.208,-122.08,-71.93,-127.5,-78.341,-75.389,131.104,160.326,-62.96,-23.783,-85.622,-71.161,14.999,-155.608,-93.228,-83.852,-86.165,-67.73,-71.93,-163.97,-91.55,-19.083,-75.389,120.35,-16.641,-97.27,112.922,-69.5,-103.62,-21.416,-78.25,-70.262,-17.83,-75.389,139.27,14.139,-72.13,110.446,130.657,127.4,-86.702,121.75,145.67,152.2,-23,-156.99,-71.729,-85.324,-69.797,-91.17,160.27,-122.12,168.12,112.308,-161.894,148.42,160.251,-16.641,-78.436,114.056,-61.64,-152.742,115.375,140.677,-85.622,158.03,154.508,14.999,0,-83.852,131.104,158.836,14.426,-62.18,-177.188,-77.656,-140.25,130.862,-89.63,-164.43,157.407,-71.183,125.407,114.056,138.528,139.918,-69.797,151.33,-61.165,138.728,-103.62,-152.742,-158.17,106.965,-103.62,114.056,120.993,14.999,-86.84,174.87,-113.5,168.12,-104.3,112.308,161.36,-71.378,-155.287,-78.436,-73.75,100.474,160.595,127.4,-78.442,121.553,112.95,131.104,140.049,-16.666,-22.566,105.423,-121.76,114.056,150.871,115.508,-155.287,158.836,113.341,-155.157,130.657,140.659,127.4,141.935,139.394,-22.083,160.326,55.708,-179.97,138.114,-16.817,-121.76,-168.03,141.38,-78.341,-87.004,124.673,140.244,55.708,-77.37,144.818,55.708,165.804,121.641,112.922,-67.73,55.708,150.094,159.443,13.897,-19.083,42.229,14.999,-61.165,159.15,160.595,158.196,-16.647,55.708,-61.664,-71.93,-78.436,-70.903,-88.269,144.013,-155.287,138.528,-72.578,139.394,-155.287,-169.944,-163.97,-155.287,138.528,130.862,155.565,-78.341,-8.155,-89.633,122.202,-70.492,-104.3,-87.004,138.523,127.4,-16.728,-78.436,25.396,14.999,178.478,160.642,109.208,-121.508,145.037,155.196,160.595,140.44,112.922,122.775,107.6,158.712,129.881,-71.409,-71.183,-152.251,-159.797,137.587,-91.35,-78.442,42.2,123.132,138.523,174.07,-156.25,-155.287,-67.73,107.6,140.303,-152.742,105.423,-71.93,-71.502,-163.97,-71.378,145.8,77.53,-19.666,-155.287,-119.029,-90.88,-70.568,14.999,139.394,14.999,121.191,-71.729,-16.647,128.08,29.2,144.893,-163.97,-84.703,138.523,43.38,14.962,14.999,-97.27,44.5,108.408,159.443,-103.62,114.056,120.8,125.407,-19.083,-120.57,107.6,129.714,-153.09,128.223,-155.287,159.15,161.36,160.642,-121.554,-152.742,-155.287,139.394,-155.287,-22.083,55.708,160.326,176.5,-77.37,-22.566,-123.5,138.728,-16.783,161.36,130.657,165.804,-85.622,55.708,-121.76,168.12,-71.729,14.139,-97.27,-72.97,-75.389,-22.083,55.708,14.426,139.759,160.642,-23,160.326,42.229,-71.349,157.407,-22.566,-19.666,-90.88,-78,130.305,112.922,-140.25,176,-130.63,123.93,-97.27,114.056,150.516,157.572,140.049,138.728,130.862,-121.229,150.516,142.854,100.474,126.047,-61.165,-84.703,150.516,110.446,110.446,124.13,100.474,160.642,-175.42,124.13,-72.794,128.83,-25.47,178.478,-156.25,-179.97,-61.664,-61.664,159.83,125.37,-169.618,-165.986,-78.436,168.12,36.33,29.2,-19.083,144.818,159.82,-83.852,158.03,-161.894,-83.852,113.341,-163.97,-61.341,-72.646,110.446,131.104,40.82,-76.4,-78.436,120.993,-155.87,154.182,109.208,-152.742,131.104,-152.742,130.862,-73.585,-129.27,-71.409,-21.783,-89.63,-101.75,155.565,-163.149,121.601,55.708,9.17,-19.666,-104.508,105.423,-91.408,160.642,168.536,-103.62,130.305,-78.598,14.962,125.407,-122.193,-161.894,138.523,130.017,128.223,131.104,151.33,0,-155.47,125.37,155.461,140.757,110.446,-174.775,144.013,-71.378,144.893,9.17,161.36,131.249,120.993,108.058,-19.083,160.642,-156.25,-86.165,-95.2,125.407,-78.598,55.708,-152.742,-155.87,161.36,138.728,112.95,113.341,29.2,0,14.399,-91.12,137.587,29.2,115.375,114.056,-87.004,140.677,-165.986,14.999,-77.656,-71.857,55.708,127.63,-17.316,106.965,-88.269,-67.73,145.161,112.308,55.708,130.299,-17.316,158.196,140.244,-19.083,152.8,114.056,-97.27,-101.75,131.104,-61.18,106.73,137.587,-61.18,127.33,-20.883,-22.566,152.203,-75.363,-69.797,-72.618,-77.986,-61.165,145.8,112.95,-153.09,-71.349,-119.03,-71.349,-85.622,175.57,109.208,-155.608,127.53,176,130.57,159.443,-77.37,42.229,-161.894,129.881,14.426,-76.4,-152.742,157.12,177.18,131.104,159.674,138.523,-90.88,9.17,14.999,158.03,157.572,159.443,157.979,-155.1,130.862,-77.58,109.879,-178.794,-86.84,-71.409,157.718,177.18,-178.794,100.474,14.999,160.642,127.33,15.213,155.62,154.808,139.963,-77.37,-19.666,14.962,-72.07,101.264,-105.32,-19.083,104.27,151.33,40.553,-152.251,147.12,125.407,-86.32,172.05,37.88,-78.442,100.474,9.17,-86.702,110.446,-26.483,-67.73,130.305,-175.63,106.965,130.592,160.27,-155.287,102.615,141.166,-18.03,131.104,142.686,152.203,-71.93,141.38,40.573,174.07,99.539,-71.93,55.708,175.57,-169.944,-135.75,14.999,0,-16.641,55.708,-164.43,123.685,105.423,114.242,112.95,125.407,171.32,-77.37,-83.767,112.922,127.33,-71.502,152.203,-155.608,-77.986,14.999,14.999,168.37,123.685,128.83,124.507,112.308,-70.568,-121.8,139.394,138.728,176.5,110.446,-89.633,-61.165,-85.324,175.632,144.893,-71.93,109.879,131.104,159.674,-71.93,-75.324,105.423,-72.618,-152.742,-155.287,12.7,-21.783,-87.004,140.049,14.999,160.595,-90.876,124.737,-72.618,150.516,0,155.373,-152.742,137.587,158.836,155.246,124.317,-71.93,-68.83,-177.188,160.326,168.12,-71.45,-87.57,-61.64,131.104,-19.083,110.446,-90.601,29.2,144.818,139.394,-140.25,145.037,14.999,131.104,168.536,157.203,139.394,175.632,26.47,107.84,161.36,160.642,55.708,155.196,145.964,110.446,-86.32,-71.93,112.308,-121.49,161.36,-67.73,167.5,138.728,138.523,-122.193,168.12,138.528,-122.18,0,-19.083,-155.608,34.621,14.426,112.308,-90.88,114.242,177.602,-155.287,-16.641,15.213,-71.93,-16.647,151.786,138.523,-17.316,14.962,14.999,-104.3,-71.93,158.03,159.443,138.523,-67.73,168.536,158.03,-121.49,-78.598,109.208,130.862,141.481,-78.442,-161.894,105.423,-91.55,-17.316,-71.409,-86.539,-83.767,-19.083,116.47,174.07,110.446,139.526,-77.656,168.346,126.5,-130.3,35.914,158.45,155.196,155.461,129.881,42.47,113.341,138.523,-16.728,-91.55,130.57,175.632,-17.316,148.42,145.504,139.918,-71.93,-166.923,109.879,114.056,100.474,114.056,178.478,168.346,140.757,105.423,-97.27,-71.93,-73.08,105.423,158.836,-26.374,100.474,-78.436,140.303,0,33.668,29.2,-91.55,145.83,-155.287,-155.361,27.16,-166.923,147.12,-70.761,-165.986,-155.608,175.632,138.036,-16.783,-20.266,160.82,55.708,158.712,125.407,151.33,130.862,140.244,-85.622,140.049,130.862,138.523,-85.622,-78.25,138.523,112.95,150.094,40.67,114.056,124.056,45.17,123.57,55.708,138.523,-16.728,-90.88,160.326,140.839,-168.03,120.993,-72.646,160.595,55.708,-86.539],0.5,null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":"#03F","fillOpacity":0.2},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[-77.53,71.082],"lng":[-179.97,179.58]}},"evals":[],"jsHooks":[]}</script>
```

:::
:::

::: {.cell}

```{.r .cell-code}
top10erupted <- exploratory_data %>%
  group_by(volcano_name, latitude, longitude) %>%
  count(eruption_category) %>%
  arrange(-n) %>%
  head(10)
leaflet() %>%
  addProviderTiles(providers$OpenTopoMap) %>%
  addCircleMarkers(lng = top10erupted$longitude, lat = top10erupted$latitude, radius = top10erupted$n/10)
```

::: {.cell-output-display}

```{=html}
<div class="leaflet html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-3d3f9425e3abbd8fe45f" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-3d3f9425e3abbd8fe45f">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["OpenTopoMap",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircleMarkers","args":[[37.748,-21.244,36.406,32.884,-39.42,63.633,19.421,56.056,-7.54,56.653],[14.999,55.708,138.523,131.104,-71.93,-19.083,-155.287,160.642,110.446,161.36],[11,9.6,7.7,7.5,7.2,6.6,5.7,5.1,5.1,5.1],null,null,{"interactive":true,"className":"","stroke":true,"color":"#03F","weight":5,"opacity":0.5,"fill":true,"fillColor":"#03F","fillOpacity":0.2},null,null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[-39.42,63.633],"lng":[-155.287,161.36]}},"evals":[],"jsHooks":[]}</script>
```

:::
:::


## Hypotheses

-   I hypothesize that volcanoes with the highest number of confirmed eruptions do not all exist in one region of the world.

-   I hypothesize that the most common method of evidence dating is Historical Observations.

## Proving Hypotheses

-   The first hypothesis can be proved with the code block above. Using ggplot, we are able to place the ten volcanoes with the highest recorded amounts of confirmed eruptions on a topographic map. We are able to see that the volcanoes are located across the map, not just in one region. Of the top ten, there are none existing in North America. There appear to be three of the top ten located in the far eastern Asia/Japan region, and another in the Indonesia. Based on this data we may be able to make inferences about where some of the most active volcanoes in the world are located.

-   The second hypothesis is examined in the code block below. It is evident that of the 20 different methods of evidence dating, historical observation is the most commonly used. However, it is worth noting that Radiocarbon and Tephrochronology were used a significant number of times as well, accounting for a total of 1436 out of 4964 total confirmed eruptions, or 29%. Additionally, 626 out of 496 confirmed eruptions (13%) have an unknown method, which could also be noted for significance.


::: {.cell}

```{.r .cell-code}
exploratory_data %>%
  count(evidence_method_dating) %>%
  arrange(-n)
```

::: {.cell-output .cell-output-stdout}
```
# A tibble: 20 × 2
   evidence_method_dating        n
   <chr>                     <int>
 1 Historical Observations    3200
 2 <NA>                        635
 3 Tephrochronology            548
 4 Radiocarbon (uncorrected)   478
 5 Radiocarbon (corrected)     419
 6 Varve Count                  85
 7 Ice Core                     52
 8 Hydrophonic                  38
 9 Magnetism                    29
10 Anthropology                 22
11 Uranium-series               18
12 Potassium-Argon              14
13 Surface Exposure             14
14 Ar/Ar                        12
15 Dendrochronology              8
16 Hydration Rind                6
17 Thermoluminescence            5
18 Uncertain                     3
19 Fission track                 2
20 Seismicity                    1
```
:::
:::
